// Mocks generated by Mockito 5.4.6 from annotations
// in cv_forge/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i23;
import 'dart:typed_data' as _i37;
import 'dart:ui' as _i28;

import 'package:cv_forge/models/ats/ats_analysis_result.dart' as _i20;
import 'package:cv_forge/models/ats/ats_extracted_document.dart' as _i18;
import 'package:cv_forge/models/ats/ats_text_node.dart' as _i19;
import 'package:cv_forge/models/backup/cv_backup_bundle.dart' as _i46;
import 'package:cv_forge/models/draft/cv_draft.dart' as _i14;
import 'package:cv_forge/models/draft/cv_section_type.dart' as _i35;
import 'package:cv_forge/models/llm/json_schema.dart' as _i51;
import 'package:cv_forge/models/llm/llm_json_response.dart' as _i21;
import 'package:cv_forge/models/render/region_profile.dart' as _i34;
import 'package:cv_forge/models/render/resolved_cv.dart' as _i42;
import 'package:cv_forge/models/settings/app_settings.dart' as _i17;
import 'package:cv_forge/models/vault/contact_basics.dart' as _i30;
import 'package:cv_forge/models/vault/cv_bullet.dart' as _i7;
import 'package:cv_forge/models/vault/cv_vault.dart' as _i4;
import 'package:cv_forge/models/vault/education.dart' as _i11;
import 'package:cv_forge/models/vault/experience.dart' as _i6;
import 'package:cv_forge/models/vault/hobby_item.dart' as _i12;
import 'package:cv_forge/models/vault/profile_link.dart' as _i5;
import 'package:cv_forge/models/vault/project.dart' as _i8;
import 'package:cv_forge/models/vault/publication.dart' as _i13;
import 'package:cv_forge/models/vault/skill.dart' as _i10;
import 'package:cv_forge/models/vault/skill_category.dart' as _i9;
import 'package:cv_forge/models/vault/year_month.dart' as _i31;
import 'package:cv_forge/services/ats_analyzer_service.dart' as _i49;
import 'package:cv_forge/services/backup_service.dart' as _i45;
import 'package:cv_forge/services/draft_service.dart' as _i32;
import 'package:cv_forge/services/file_download_service.dart' as _i36;
import 'package:cv_forge/services/file_upload_service.dart' as _i47;
import 'package:cv_forge/services/font_service.dart' as _i40;
import 'package:cv_forge/services/llm_service.dart' as _i50;
import 'package:cv_forge/services/local_storage_service.dart' as _i3;
import 'package:cv_forge/services/pdf_export_service.dart' as _i41;
import 'package:cv_forge/services/pdf_extraction_service.dart' as _i48;
import 'package:cv_forge/services/settings_service.dart' as _i44;
import 'package:cv_forge/services/template_registry_service.dart' as _i39;
import 'package:cv_forge/services/vault_service.dart' as _i29;
import 'package:cv_forge/templates/cv_template.dart' as _i15;
import 'package:cv_forge/templates/design/cv_font_set.dart' as _i16;
import 'package:file_saver/file_saver.dart' as _i38;
import 'package:flutter/material.dart' as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i33;
import 'package:pdf/pdf.dart' as _i43;
import 'package:stacked/stacked.dart' as _i2;
import 'package:stacked_services/src/dialog/dialog_service.dart' as _i25;
import 'package:stacked_services/src/models/overlay_request.dart' as _i26;
import 'package:stacked_services/src/models/overlay_response.dart' as _i27;
import 'package:stacked_services/src/navigation/router_service.dart' as _i22;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRootStackRouter_0 extends _i1.SmartFake
    implements _i2.RootStackRouter {
  _FakeRootStackRouter_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteData_1 extends _i1.SmartFake implements _i2.RouteData {
  _FakeRouteData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoutingController_2 extends _i1.SmartFake
    implements _i2.RoutingController {
  _FakeRoutingController_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalStorageService_3 extends _i1.SmartFake
    implements _i3.LocalStorageService {
  _FakeLocalStorageService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCvVault_4 extends _i1.SmartFake implements _i4.CvVault {
  _FakeCvVault_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReactiveValue_5<T> extends _i1.SmartFake
    implements _i2.ReactiveValue<T> {
  _FakeReactiveValue_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileLink_6 extends _i1.SmartFake implements _i5.ProfileLink {
  _FakeProfileLink_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExperience_7 extends _i1.SmartFake implements _i6.Experience {
  _FakeExperience_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCvBullet_8 extends _i1.SmartFake implements _i7.CvBullet {
  _FakeCvBullet_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProject_9 extends _i1.SmartFake implements _i8.Project {
  _FakeProject_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSkillCategory_10 extends _i1.SmartFake implements _i9.SkillCategory {
  _FakeSkillCategory_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSkill_11 extends _i1.SmartFake implements _i10.Skill {
  _FakeSkill_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEducation_12 extends _i1.SmartFake implements _i11.Education {
  _FakeEducation_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHobbyItem_13 extends _i1.SmartFake implements _i12.HobbyItem {
  _FakeHobbyItem_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePublication_14 extends _i1.SmartFake implements _i13.Publication {
  _FakePublication_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCvDraft_15 extends _i1.SmartFake implements _i14.CvDraft {
  _FakeCvDraft_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCvTemplate_16 extends _i1.SmartFake implements _i15.CvTemplate {
  _FakeCvTemplate_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCvFontSet_17 extends _i1.SmartFake implements _i16.CvFontSet {
  _FakeCvFontSet_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppSettings_18 extends _i1.SmartFake implements _i17.AppSettings {
  _FakeAppSettings_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtsExtractedDocument_19 extends _i1.SmartFake
    implements _i18.AtsExtractedDocument {
  _FakeAtsExtractedDocument_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtsTextMatrix_20 extends _i1.SmartFake
    implements _i19.AtsTextMatrix {
  _FakeAtsTextMatrix_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtsAnalysisResult_21 extends _i1.SmartFake
    implements _i20.AtsAnalysisResult {
  _FakeAtsAnalysisResult_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLlmJsonResponse_22 extends _i1.SmartFake
    implements _i21.LlmJsonResponse {
  _FakeLlmJsonResponse_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RouterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouterService extends _i1.Mock implements _i22.RouterService {
  @override
  _i2.RootStackRouter get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeRootStackRouter_0(
              this,
              Invocation.getter(#router),
            ),
            returnValueForMissingStub: _FakeRootStackRouter_0(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i2.RootStackRouter);

  @override
  List<_i2.StackedPage<dynamic>> get stack =>
      (super.noSuchMethod(
            Invocation.getter(#stack),
            returnValue: <_i2.StackedPage<dynamic>>[],
            returnValueForMissingStub: <_i2.StackedPage<dynamic>>[],
          )
          as List<_i2.StackedPage<dynamic>>);

  @override
  _i2.RouteData get topRoute =>
      (super.noSuchMethod(
            Invocation.getter(#topRoute),
            returnValue: _FakeRouteData_1(this, Invocation.getter(#topRoute)),
            returnValueForMissingStub: _FakeRouteData_1(
              this,
              Invocation.getter(#topRoute),
            ),
          )
          as _i2.RouteData);

  @override
  set router(_i2.RootStackRouter? value) => super.noSuchMethod(
    Invocation.setter(#router, value),
    returnValueForMissingStub: null,
  );

  @override
  dynamic setRouter(_i2.RootStackRouter? router) => super.noSuchMethod(
    Invocation.method(#setRouter, [router]),
    returnValueForMissingStub: null,
  );

  @override
  _i23.Future<dynamic> navigateTo(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#navigateTo, [route], {#onFailure: onFailure}),
            returnValue: _i23.Future<dynamic>.value(),
            returnValueForMissingStub: _i23.Future<dynamic>.value(),
          )
          as _i23.Future<dynamic>);

  @override
  _i23.Future<void> navigateToPath({
    required String? path,
    bool? includePrefixMatches = false,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#navigateToPath, [], {
              #path: path,
              #includePrefixMatches: includePrefixMatches,
              #onFailure: onFailure,
            }),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<T?> navigateWithTransition<T extends Object?>(
    _i24.Widget? widget, {
    _i24.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigateWithTransition,
              [widget],
              {
                #transitionBuilder: transitionBuilder,
                #fullscreenDialog: fullscreenDialog,
                #transitionDuration: transitionDuration,
              },
            ),
            returnValue: _i23.Future<T?>.value(),
            returnValueForMissingStub: _i23.Future<T?>.value(),
          )
          as _i23.Future<T?>);

  @override
  _i23.Future<T?> replaceWith<T extends Object?>(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replaceWith, [route], {#onFailure: onFailure}),
            returnValue: _i23.Future<T?>.value(),
            returnValueForMissingStub: _i23.Future<T?>.value(),
          )
          as _i23.Future<T?>);

  @override
  _i23.Future<void> clearStackAndShow(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #clearStackAndShow,
              [route],
              {#onFailure: onFailure},
            ),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> clearStackAndShowView(
    _i24.Widget? widget, {
    _i24.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #clearStackAndShowView,
              [widget],
              {
                #transitionBuilder: transitionBuilder,
                #fullscreenDialog: fullscreenDialog,
                #transitionDuration: transitionDuration,
              },
            ),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  void popForced<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#popForced, [result]),
    returnValueForMissingStub: null,
  );

  @override
  _i23.Future<bool> pop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
            Invocation.method(#pop, [result]),
            returnValue: _i23.Future<bool>.value(false),
            returnValueForMissingStub: _i23.Future<bool>.value(false),
          )
          as _i23.Future<bool>);

  @override
  void back<T extends Object?>({T? result}) => super.noSuchMethod(
    Invocation.method(#back, [], {#result: result}),
    returnValueForMissingStub: null,
  );

  @override
  _i2.RoutingController topMostRouter({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
            Invocation.method(#topMostRouter, [], {
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: _FakeRoutingController_2(
              this,
              Invocation.method(#topMostRouter, [], {
                #ignorePagelessRoutes: ignorePagelessRoutes,
              }),
            ),
            returnValueForMissingStub: _FakeRoutingController_2(
              this,
              Invocation.method(#topMostRouter, [], {
                #ignorePagelessRoutes: ignorePagelessRoutes,
              }),
            ),
          )
          as _i2.RoutingController);

  @override
  _i23.Future<T?> pushNativeRoute<T extends Object?>(_i24.Route<T>? route) =>
      (super.noSuchMethod(
            Invocation.method(#pushNativeRoute, [route]),
            returnValue: _i23.Future<T?>.value(),
            returnValueForMissingStub: _i23.Future<T?>.value(),
          )
          as _i23.Future<T?>);
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i25.DialogService {
  @override
  void registerCustomDialogBuilders(
    Map<dynamic, _i25.DialogBuilder>? builders,
  ) => super.noSuchMethod(
    Invocation.method(#registerCustomDialogBuilders, [builders]),
    returnValueForMissingStub: null,
  );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i24.Widget Function(
      _i24.BuildContext,
      _i26.DialogRequest<dynamic>,
      dynamic Function(_i27.DialogResponse<dynamic>),
    )?
    builder,
  }) => super.noSuchMethod(
    Invocation.method(#registerCustomDialogBuilder, [], {
      #variant: variant,
      #builder: builder,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i23.Future<_i27.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i28.Color? cancelTitleColor,
    String? buttonTitle = 'Ok',
    _i28.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i24.RouteSettings? routeSettings,
    _i24.GlobalKey<_i24.NavigatorState>? navigatorKey,
    _i25.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showDialog, [], {
              #title: title,
              #description: description,
              #cancelTitle: cancelTitle,
              #cancelTitleColor: cancelTitleColor,
              #buttonTitle: buttonTitle,
              #buttonTitleColor: buttonTitleColor,
              #barrierDismissible: barrierDismissible,
              #routeSettings: routeSettings,
              #navigatorKey: navigatorKey,
              #dialogPlatform: dialogPlatform,
            }),
            returnValue: _i23.Future<_i27.DialogResponse<dynamic>?>.value(),
            returnValueForMissingStub:
                _i23.Future<_i27.DialogResponse<dynamic>?>.value(),
          )
          as _i23.Future<_i27.DialogResponse<dynamic>?>);

  @override
  _i23.Future<_i27.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i28.Color? barrierColor = const _i28.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = '',
    bool? useSafeArea = true,
    _i24.RouteSettings? routeSettings,
    _i24.GlobalKey<_i24.NavigatorState>? navigatorKey,
    _i24.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showCustomDialog, [], {
              #variant: variant,
              #title: title,
              #description: description,
              #hasImage: hasImage,
              #imageUrl: imageUrl,
              #showIconInMainButton: showIconInMainButton,
              #mainButtonTitle: mainButtonTitle,
              #showIconInSecondaryButton: showIconInSecondaryButton,
              #secondaryButtonTitle: secondaryButtonTitle,
              #showIconInAdditionalButton: showIconInAdditionalButton,
              #additionalButtonTitle: additionalButtonTitle,
              #takesInput: takesInput,
              #barrierColor: barrierColor,
              #barrierDismissible: barrierDismissible,
              #barrierLabel: barrierLabel,
              #useSafeArea: useSafeArea,
              #routeSettings: routeSettings,
              #navigatorKey: navigatorKey,
              #transitionBuilder: transitionBuilder,
              #customData: customData,
              #data: data,
            }),
            returnValue: _i23.Future<_i27.DialogResponse<T>?>.value(),
            returnValueForMissingStub:
                _i23.Future<_i27.DialogResponse<T>?>.value(),
          )
          as _i23.Future<_i27.DialogResponse<T>?>);

  @override
  _i23.Future<_i27.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = 'Cancel',
    _i28.Color? cancelTitleColor,
    String? confirmationTitle = 'Ok',
    _i28.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i24.RouteSettings? routeSettings,
    _i25.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showConfirmationDialog, [], {
              #title: title,
              #description: description,
              #cancelTitle: cancelTitle,
              #cancelTitleColor: cancelTitleColor,
              #confirmationTitle: confirmationTitle,
              #confirmationTitleColor: confirmationTitleColor,
              #barrierDismissible: barrierDismissible,
              #routeSettings: routeSettings,
              #dialogPlatform: dialogPlatform,
            }),
            returnValue: _i23.Future<_i27.DialogResponse<dynamic>?>.value(),
            returnValueForMissingStub:
                _i23.Future<_i27.DialogResponse<dynamic>?>.value(),
          )
          as _i23.Future<_i27.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i27.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(#completeDialog, [response]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i3.LocalStorageService {
  @override
  _i23.Future<void> ensureInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#ensureInitialized, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<String?> read(String? boxName, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [boxName, key]),
            returnValue: _i23.Future<String?>.value(),
            returnValueForMissingStub: _i23.Future<String?>.value(),
          )
          as _i23.Future<String?>);

  @override
  _i23.Future<void> write(String? boxName, String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#write, [boxName, key, value]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> delete(String? boxName, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [boxName, key]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);
}

/// A class which mocks [VaultService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaultService extends _i1.Mock implements _i29.VaultService {
  @override
  _i3.LocalStorageService get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeLocalStorageService_3(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeLocalStorageService_3(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i3.LocalStorageService);

  @override
  _i4.CvVault get vault =>
      (super.noSuchMethod(
            Invocation.getter(#vault),
            returnValue: _FakeCvVault_4(this, Invocation.getter(#vault)),
            returnValueForMissingStub: _FakeCvVault_4(
              this,
              Invocation.getter(#vault),
            ),
          )
          as _i4.CvVault);

  @override
  int get listenersCount =>
      (super.noSuchMethod(
            Invocation.getter(#listenersCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i2.ReactiveValue<Object?> get persistErrorNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#persistErrorNotifier),
            returnValue: _FakeReactiveValue_5<Object?>(
              this,
              Invocation.getter(#persistErrorNotifier),
            ),
            returnValueForMissingStub: _FakeReactiveValue_5<Object?>(
              this,
              Invocation.getter(#persistErrorNotifier),
            ),
          )
          as _i2.ReactiveValue<Object?>);

  @override
  set persistError(Object? value) => super.noSuchMethod(
    Invocation.setter(#persistError, value),
    returnValueForMissingStub: null,
  );

  @override
  _i23.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> loadFromStorage() =>
      (super.noSuchMethod(
            Invocation.method(#loadFromStorage, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> loadExampleVault() =>
      (super.noSuchMethod(
            Invocation.method(#loadExampleVault, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> updateBasics(_i30.ContactBasics? basics) =>
      (super.noSuchMethod(
            Invocation.method(#updateBasics, [basics]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i5.ProfileLink> addProfileLink({
    required String? label,
    required String? url,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addProfileLink, [], {#label: label, #url: url}),
            returnValue: _i23.Future<_i5.ProfileLink>.value(
              _FakeProfileLink_6(
                this,
                Invocation.method(#addProfileLink, [], {
                  #label: label,
                  #url: url,
                }),
              ),
            ),
            returnValueForMissingStub: _i23.Future<_i5.ProfileLink>.value(
              _FakeProfileLink_6(
                this,
                Invocation.method(#addProfileLink, [], {
                  #label: label,
                  #url: url,
                }),
              ),
            ),
          )
          as _i23.Future<_i5.ProfileLink>);

  @override
  _i23.Future<void> updateProfileLink(_i5.ProfileLink? link) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfileLink, [link]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> deleteProfileLink(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfileLink, [id]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> updateReferencesNote(String? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateReferencesNote, [note]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i6.Experience> addExperience({
    required String? role,
    required String? company,
    required String? location,
    required _i31.YearMonth? start,
    _i31.YearMonth? end,
    bool? isCurrent = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addExperience, [], {
              #role: role,
              #company: company,
              #location: location,
              #start: start,
              #end: end,
              #isCurrent: isCurrent,
            }),
            returnValue: _i23.Future<_i6.Experience>.value(
              _FakeExperience_7(
                this,
                Invocation.method(#addExperience, [], {
                  #role: role,
                  #company: company,
                  #location: location,
                  #start: start,
                  #end: end,
                  #isCurrent: isCurrent,
                }),
              ),
            ),
            returnValueForMissingStub: _i23.Future<_i6.Experience>.value(
              _FakeExperience_7(
                this,
                Invocation.method(#addExperience, [], {
                  #role: role,
                  #company: company,
                  #location: location,
                  #start: start,
                  #end: end,
                  #isCurrent: isCurrent,
                }),
              ),
            ),
          )
          as _i23.Future<_i6.Experience>);

  @override
  _i23.Future<void> updateExperience(_i6.Experience? experience) =>
      (super.noSuchMethod(
            Invocation.method(#updateExperience, [experience]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> deleteExperience(String? experienceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExperience, [experienceId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> groupExperience(
    String? experienceId,
    String? withExperienceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#groupExperience, [
              experienceId,
              withExperienceId,
            ]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i7.CvBullet> addBullet(
    String? experienceId, {
    String? label,
    required String? text,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addBullet,
              [experienceId],
              {#label: label, #text: text},
            ),
            returnValue: _i23.Future<_i7.CvBullet>.value(
              _FakeCvBullet_8(
                this,
                Invocation.method(
                  #addBullet,
                  [experienceId],
                  {#label: label, #text: text},
                ),
              ),
            ),
            returnValueForMissingStub: _i23.Future<_i7.CvBullet>.value(
              _FakeCvBullet_8(
                this,
                Invocation.method(
                  #addBullet,
                  [experienceId],
                  {#label: label, #text: text},
                ),
              ),
            ),
          )
          as _i23.Future<_i7.CvBullet>);

  @override
  _i23.Future<void> updateBullet(String? experienceId, _i7.CvBullet? bullet) =>
      (super.noSuchMethod(
            Invocation.method(#updateBullet, [experienceId, bullet]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> deleteBullet(String? experienceId, String? bulletId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBullet, [experienceId, bulletId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> reorderBullets(
    String? experienceId,
    List<String>? orderedBulletIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderBullets, [
              experienceId,
              orderedBulletIds,
            ]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i8.Project> addProject({required String? title, String? link}) =>
      (super.noSuchMethod(
            Invocation.method(#addProject, [], {#title: title, #link: link}),
            returnValue: _i23.Future<_i8.Project>.value(
              _FakeProject_9(
                this,
                Invocation.method(#addProject, [], {
                  #title: title,
                  #link: link,
                }),
              ),
            ),
            returnValueForMissingStub: _i23.Future<_i8.Project>.value(
              _FakeProject_9(
                this,
                Invocation.method(#addProject, [], {
                  #title: title,
                  #link: link,
                }),
              ),
            ),
          )
          as _i23.Future<_i8.Project>);

  @override
  _i23.Future<void> updateProject(_i8.Project? project) =>
      (super.noSuchMethod(
            Invocation.method(#updateProject, [project]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> deleteProject(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProject, [projectId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i7.CvBullet> addProjectBullet(
    String? projectId, {
    String? label,
    required String? text,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addProjectBullet,
              [projectId],
              {#label: label, #text: text},
            ),
            returnValue: _i23.Future<_i7.CvBullet>.value(
              _FakeCvBullet_8(
                this,
                Invocation.method(
                  #addProjectBullet,
                  [projectId],
                  {#label: label, #text: text},
                ),
              ),
            ),
            returnValueForMissingStub: _i23.Future<_i7.CvBullet>.value(
              _FakeCvBullet_8(
                this,
                Invocation.method(
                  #addProjectBullet,
                  [projectId],
                  {#label: label, #text: text},
                ),
              ),
            ),
          )
          as _i23.Future<_i7.CvBullet>);

  @override
  _i23.Future<void> updateProjectBullet(
    String? projectId,
    _i7.CvBullet? bullet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProjectBullet, [projectId, bullet]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> deleteProjectBullet(String? projectId, String? bulletId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProjectBullet, [projectId, bulletId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> reorderProjectBullets(
    String? projectId,
    List<String>? orderedBulletIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderProjectBullets, [
              projectId,
              orderedBulletIds,
            ]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i9.SkillCategory> addSkillCategory(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#addSkillCategory, [name]),
            returnValue: _i23.Future<_i9.SkillCategory>.value(
              _FakeSkillCategory_10(
                this,
                Invocation.method(#addSkillCategory, [name]),
              ),
            ),
            returnValueForMissingStub: _i23.Future<_i9.SkillCategory>.value(
              _FakeSkillCategory_10(
                this,
                Invocation.method(#addSkillCategory, [name]),
              ),
            ),
          )
          as _i23.Future<_i9.SkillCategory>);

  @override
  _i23.Future<void> updateSkillCategory(_i9.SkillCategory? category) =>
      (super.noSuchMethod(
            Invocation.method(#updateSkillCategory, [category]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> deleteSkillCategory(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSkillCategory, [categoryId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i10.Skill> addSkill(String? categoryId, String? label) =>
      (super.noSuchMethod(
            Invocation.method(#addSkill, [categoryId, label]),
            returnValue: _i23.Future<_i10.Skill>.value(
              _FakeSkill_11(
                this,
                Invocation.method(#addSkill, [categoryId, label]),
              ),
            ),
            returnValueForMissingStub: _i23.Future<_i10.Skill>.value(
              _FakeSkill_11(
                this,
                Invocation.method(#addSkill, [categoryId, label]),
              ),
            ),
          )
          as _i23.Future<_i10.Skill>);

  @override
  _i23.Future<void> updateSkill(String? categoryId, _i10.Skill? skill) =>
      (super.noSuchMethod(
            Invocation.method(#updateSkill, [categoryId, skill]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> deleteSkill(String? categoryId, String? skillId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSkill, [categoryId, skillId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i11.Education> addEducation({
    required String? qualification,
    required String? institution,
    String? location,
    int? year,
    String? grade,
    String? details,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addEducation, [], {
              #qualification: qualification,
              #institution: institution,
              #location: location,
              #year: year,
              #grade: grade,
              #details: details,
            }),
            returnValue: _i23.Future<_i11.Education>.value(
              _FakeEducation_12(
                this,
                Invocation.method(#addEducation, [], {
                  #qualification: qualification,
                  #institution: institution,
                  #location: location,
                  #year: year,
                  #grade: grade,
                  #details: details,
                }),
              ),
            ),
            returnValueForMissingStub: _i23.Future<_i11.Education>.value(
              _FakeEducation_12(
                this,
                Invocation.method(#addEducation, [], {
                  #qualification: qualification,
                  #institution: institution,
                  #location: location,
                  #year: year,
                  #grade: grade,
                  #details: details,
                }),
              ),
            ),
          )
          as _i23.Future<_i11.Education>);

  @override
  _i23.Future<void> updateEducation(_i11.Education? education) =>
      (super.noSuchMethod(
            Invocation.method(#updateEducation, [education]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> deleteEducation(String? educationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEducation, [educationId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i12.HobbyItem> addHobby(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#addHobby, [text]),
            returnValue: _i23.Future<_i12.HobbyItem>.value(
              _FakeHobbyItem_13(this, Invocation.method(#addHobby, [text])),
            ),
            returnValueForMissingStub: _i23.Future<_i12.HobbyItem>.value(
              _FakeHobbyItem_13(this, Invocation.method(#addHobby, [text])),
            ),
          )
          as _i23.Future<_i12.HobbyItem>);

  @override
  _i23.Future<void> updateHobby(_i12.HobbyItem? hobby) =>
      (super.noSuchMethod(
            Invocation.method(#updateHobby, [hobby]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> deleteHobby(String? hobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHobby, [hobbyId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> replaceAll(_i4.CvVault? vault) =>
      (super.noSuchMethod(
            Invocation.method(#replaceAll, [vault]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i13.Publication> addPublication({
    required String? title,
    String? citation,
    String? link,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addPublication, [], {
              #title: title,
              #citation: citation,
              #link: link,
            }),
            returnValue: _i23.Future<_i13.Publication>.value(
              _FakePublication_14(
                this,
                Invocation.method(#addPublication, [], {
                  #title: title,
                  #citation: citation,
                  #link: link,
                }),
              ),
            ),
            returnValueForMissingStub: _i23.Future<_i13.Publication>.value(
              _FakePublication_14(
                this,
                Invocation.method(#addPublication, [], {
                  #title: title,
                  #citation: citation,
                  #link: link,
                }),
              ),
            ),
          )
          as _i23.Future<_i13.Publication>);

  @override
  _i23.Future<void> updatePublication(_i13.Publication? publication) =>
      (super.noSuchMethod(
            Invocation.method(#updatePublication, [publication]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> deletePublication(String? publicationId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePublication, [publicationId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> flushPendingWrites() =>
      (super.noSuchMethod(
            Invocation.method(#flushPendingWrites, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> writeToStorage(_i4.CvVault? value) =>
      (super.noSuchMethod(
            Invocation.method(#writeToStorage, [value]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(#listenToReactiveValues, [reactiveValues]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i23.Future<void> ready() =>
      (super.noSuchMethod(
            Invocation.method(#ready, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  void scheduleWrite(_i4.CvVault? target) => super.noSuchMethod(
    Invocation.method(#scheduleWrite, [target]),
    returnValueForMissingStub: null,
  );

  @override
  _i23.Future<void> persistNow(_i4.CvVault? fallback) =>
      (super.noSuchMethod(
            Invocation.method(#persistNow, [fallback]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> persistImmediately(_i4.CvVault? value) =>
      (super.noSuchMethod(
            Invocation.method(#persistImmediately, [value]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> quarantine(String? box, String? originalKey, String? raw) =>
      (super.noSuchMethod(
            Invocation.method(#quarantine, [box, originalKey, raw]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);
}

/// A class which mocks [DraftService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDraftService extends _i1.Mock implements _i32.DraftService {
  @override
  _i3.LocalStorageService get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeLocalStorageService_3(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeLocalStorageService_3(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i3.LocalStorageService);

  @override
  List<_i14.CvDraft> get drafts =>
      (super.noSuchMethod(
            Invocation.getter(#drafts),
            returnValue: <_i14.CvDraft>[],
            returnValueForMissingStub: <_i14.CvDraft>[],
          )
          as List<_i14.CvDraft>);

  @override
  _i14.CvDraft get draft =>
      (super.noSuchMethod(
            Invocation.getter(#draft),
            returnValue: _FakeCvDraft_15(this, Invocation.getter(#draft)),
            returnValueForMissingStub: _FakeCvDraft_15(
              this,
              Invocation.getter(#draft),
            ),
          )
          as _i14.CvDraft);

  @override
  bool get isFreshDraft =>
      (super.noSuchMethod(
            Invocation.getter(#isFreshDraft),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get listenersCount =>
      (super.noSuchMethod(
            Invocation.getter(#listenersCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i2.ReactiveValue<Object?> get persistErrorNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#persistErrorNotifier),
            returnValue: _FakeReactiveValue_5<Object?>(
              this,
              Invocation.getter(#persistErrorNotifier),
            ),
            returnValueForMissingStub: _FakeReactiveValue_5<Object?>(
              this,
              Invocation.getter(#persistErrorNotifier),
            ),
          )
          as _i2.ReactiveValue<Object?>);

  @override
  set persistError(Object? value) => super.noSuchMethod(
    Invocation.setter(#persistError, value),
    returnValueForMissingStub: null,
  );

  @override
  _i23.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> loadFromStorage() =>
      (super.noSuchMethod(
            Invocation.method(#loadFromStorage, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<String> createDraft({
    required String? name,
    String? notes = '',
    String? templateId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDraft, [], {
              #name: name,
              #notes: notes,
              #templateId: templateId,
            }),
            returnValue: _i23.Future<String>.value(
              _i33.dummyValue<String>(
                this,
                Invocation.method(#createDraft, [], {
                  #name: name,
                  #notes: notes,
                  #templateId: templateId,
                }),
              ),
            ),
            returnValueForMissingStub: _i23.Future<String>.value(
              _i33.dummyValue<String>(
                this,
                Invocation.method(#createDraft, [], {
                  #name: name,
                  #notes: notes,
                  #templateId: templateId,
                }),
              ),
            ),
          )
          as _i23.Future<String>);

  @override
  _i23.Future<void> openDraft(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#openDraft, [id]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> updateDraftDetails(
    String? id, {
    required String? name,
    required String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateDraftDetails,
              [id],
              {#name: name, #notes: notes},
            ),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<String> duplicateDraft(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#duplicateDraft, [id]),
            returnValue: _i23.Future<String>.value(
              _i33.dummyValue<String>(
                this,
                Invocation.method(#duplicateDraft, [id]),
              ),
            ),
            returnValueForMissingStub: _i23.Future<String>.value(
              _i33.dummyValue<String>(
                this,
                Invocation.method(#duplicateDraft, [id]),
              ),
            ),
          )
          as _i23.Future<String>);

  @override
  _i23.Future<void> deleteDraft(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDraft, [id]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> replaceAll(
    List<_i14.CvDraft>? drafts, {
    required String? activeDraftId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceAll,
              [drafts],
              {#activeDraftId: activeDraftId},
            ),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setTemplate(String? templateId) =>
      (super.noSuchMethod(
            Invocation.method(#setTemplate, [templateId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setRegion(_i34.RegionProfile? region) =>
      (super.noSuchMethod(
            Invocation.method(#setRegion, [region]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> selectAllFromVault({
    required List<String>? experienceIds,
    required Map<String, List<String>>? bulletIds,
    required List<String>? projectIds,
    required Map<String, List<String>>? projectBulletIds,
    required List<String>? skillIds,
    required List<String>? educationIds,
    required List<String>? hobbyIds,
    required List<String>? publicationIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectAllFromVault, [], {
              #experienceIds: experienceIds,
              #bulletIds: bulletIds,
              #projectIds: projectIds,
              #projectBulletIds: projectBulletIds,
              #skillIds: skillIds,
              #educationIds: educationIds,
              #hobbyIds: hobbyIds,
              #publicationIds: publicationIds,
            }),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setExperienceIncluded(
    String? experienceId, {
    required bool? included,
    List<String>? bulletIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setExperienceIncluded,
              [experienceId],
              {#included: included, #bulletIds: bulletIds},
            ),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setBulletsForExperience(
    String? experienceId,
    List<String>? bulletIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setBulletsForExperience, [
              experienceId,
              bulletIds,
            ]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setProjectIncluded(
    String? projectId, {
    required bool? included,
    List<String>? bulletIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setProjectIncluded,
              [projectId],
              {#included: included, #bulletIds: bulletIds},
            ),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setBulletsForProject(
    String? projectId,
    List<String>? bulletIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setBulletsForProject, [projectId, bulletIds]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setSkillIncluded(
    String? skillId, {
    required bool? included,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setSkillIncluded,
              [skillId],
              {#included: included},
            ),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setEducationIncluded(
    String? educationId, {
    required bool? included,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setEducationIncluded,
              [educationId],
              {#included: included},
            ),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setHobbyIncluded(
    String? hobbyId, {
    required bool? included,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setHobbyIncluded,
              [hobbyId],
              {#included: included},
            ),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setPublicationIncluded(
    String? publicationId, {
    required bool? included,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setPublicationIncluded,
              [publicationId],
              {#included: included},
            ),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setSectionHidden(
    _i35.CvSectionType? type, {
    required bool? hidden,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSectionHidden, [type], {#hidden: hidden}),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setTailoredSummary(String? summary) =>
      (super.noSuchMethod(
            Invocation.method(#setTailoredSummary, [summary]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setBulletOverride(String? bulletId, String? text) =>
      (super.noSuchMethod(
            Invocation.method(#setBulletOverride, [bulletId, text]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setHeadlineOverride(String? headline) =>
      (super.noSuchMethod(
            Invocation.method(#setHeadlineOverride, [headline]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setReferencesOverride(String? references) =>
      (super.noSuchMethod(
            Invocation.method(#setReferencesOverride, [references]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setEducationDetailsOverride(
    String? educationId,
    String? text,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setEducationDetailsOverride, [
              educationId,
              text,
            ]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> flushPendingWrites() =>
      (super.noSuchMethod(
            Invocation.method(#flushPendingWrites, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> writeToStorage(_i14.CvDraft? value) =>
      (super.noSuchMethod(
            Invocation.method(#writeToStorage, [value]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(#listenToReactiveValues, [reactiveValues]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i23.Future<void> ready() =>
      (super.noSuchMethod(
            Invocation.method(#ready, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  void scheduleWrite(_i14.CvDraft? target) => super.noSuchMethod(
    Invocation.method(#scheduleWrite, [target]),
    returnValueForMissingStub: null,
  );

  @override
  _i23.Future<void> persistNow(_i14.CvDraft? fallback) =>
      (super.noSuchMethod(
            Invocation.method(#persistNow, [fallback]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> persistImmediately(_i14.CvDraft? value) =>
      (super.noSuchMethod(
            Invocation.method(#persistImmediately, [value]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> quarantine(String? box, String? originalKey, String? raw) =>
      (super.noSuchMethod(
            Invocation.method(#quarantine, [box, originalKey, raw]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);
}

/// A class which mocks [FileDownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileDownloadService extends _i1.Mock
    implements _i36.FileDownloadService {
  @override
  _i23.Future<void> saveFile({
    required String? nameWithoutExtension,
    required _i37.Uint8List? bytes,
    required String? extension,
    required _i38.MimeType? mimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveFile, [], {
              #nameWithoutExtension: nameWithoutExtension,
              #bytes: bytes,
              #extension: extension,
              #mimeType: mimeType,
            }),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);
}

/// A class which mocks [TemplateRegistryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTemplateRegistryService extends _i1.Mock
    implements _i39.TemplateRegistryService {
  @override
  _i15.CvTemplate get defaultTemplate =>
      (super.noSuchMethod(
            Invocation.getter(#defaultTemplate),
            returnValue: _FakeCvTemplate_16(
              this,
              Invocation.getter(#defaultTemplate),
            ),
            returnValueForMissingStub: _FakeCvTemplate_16(
              this,
              Invocation.getter(#defaultTemplate),
            ),
          )
          as _i15.CvTemplate);

  @override
  List<_i15.CvTemplate> get available =>
      (super.noSuchMethod(
            Invocation.getter(#available),
            returnValue: <_i15.CvTemplate>[],
            returnValueForMissingStub: <_i15.CvTemplate>[],
          )
          as List<_i15.CvTemplate>);

  @override
  _i15.CvTemplate byId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#byId, [id]),
            returnValue: _FakeCvTemplate_16(
              this,
              Invocation.method(#byId, [id]),
            ),
            returnValueForMissingStub: _FakeCvTemplate_16(
              this,
              Invocation.method(#byId, [id]),
            ),
          )
          as _i15.CvTemplate);
}

/// A class which mocks [FontService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFontService extends _i1.Mock implements _i40.FontService {
  @override
  _i23.Future<_i16.CvFontSet> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i23.Future<_i16.CvFontSet>.value(
              _FakeCvFontSet_17(this, Invocation.method(#load, [])),
            ),
            returnValueForMissingStub: _i23.Future<_i16.CvFontSet>.value(
              _FakeCvFontSet_17(this, Invocation.method(#load, [])),
            ),
          )
          as _i23.Future<_i16.CvFontSet>);

  @override
  _i23.Future<void> warmUp() =>
      (super.noSuchMethod(
            Invocation.method(#warmUp, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);
}

/// A class which mocks [PdfExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfExportService extends _i1.Mock implements _i41.PdfExportService {
  @override
  _i23.Future<void> export({
    required _i42.ResolvedCv? cv,
    required String? templateId,
    required String? fullName,
    required String? draftName,
    _i43.PdfPageFormat? format = _i43.PdfPageFormat.a4,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#export, [], {
              #cv: cv,
              #templateId: templateId,
              #fullName: fullName,
              #draftName: draftName,
              #format: format,
            }),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i37.Uint8List> render({
    required _i42.ResolvedCv? cv,
    required String? templateId,
    _i43.PdfPageFormat? format = _i43.PdfPageFormat.a4,
    bool? compress = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#render, [], {
              #cv: cv,
              #templateId: templateId,
              #format: format,
              #compress: compress,
            }),
            returnValue: _i23.Future<_i37.Uint8List>.value(_i37.Uint8List(0)),
            returnValueForMissingStub: _i23.Future<_i37.Uint8List>.value(
              _i37.Uint8List(0),
            ),
          )
          as _i23.Future<_i37.Uint8List>);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i44.SettingsService {
  @override
  _i3.LocalStorageService get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeLocalStorageService_3(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeLocalStorageService_3(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i3.LocalStorageService);

  @override
  _i17.AppSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeAppSettings_18(
              this,
              Invocation.getter(#settings),
            ),
            returnValueForMissingStub: _FakeAppSettings_18(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i17.AppSettings);

  @override
  int get listenersCount =>
      (super.noSuchMethod(
            Invocation.getter(#listenersCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i2.ReactiveValue<Object?> get persistErrorNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#persistErrorNotifier),
            returnValue: _FakeReactiveValue_5<Object?>(
              this,
              Invocation.getter(#persistErrorNotifier),
            ),
            returnValueForMissingStub: _FakeReactiveValue_5<Object?>(
              this,
              Invocation.getter(#persistErrorNotifier),
            ),
          )
          as _i2.ReactiveValue<Object?>);

  @override
  set persistError(Object? value) => super.noSuchMethod(
    Invocation.setter(#persistError, value),
    returnValueForMissingStub: null,
  );

  @override
  _i23.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setCopilotProvider(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#setCopilotProvider, [providerId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setCopilotModel(String? modelId) =>
      (super.noSuchMethod(
            Invocation.method(#setCopilotModel, [modelId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> setRememberApiKey(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setRememberApiKey, [value]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<String?> apiKeyFor(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#apiKeyFor, [providerId]),
            returnValue: _i23.Future<String?>.value(),
            returnValueForMissingStub: _i23.Future<String?>.value(),
          )
          as _i23.Future<String?>);

  @override
  _i23.Future<void> setApiKey(String? providerId, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#setApiKey, [providerId, key]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> clearApiKey(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#clearApiKey, [providerId]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> loadFromStorage() =>
      (super.noSuchMethod(
            Invocation.method(#loadFromStorage, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> writeToStorage(_i17.AppSettings? value) =>
      (super.noSuchMethod(
            Invocation.method(#writeToStorage, [value]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(#listenToReactiveValues, [reactiveValues]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i23.Future<void> ready() =>
      (super.noSuchMethod(
            Invocation.method(#ready, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  void scheduleWrite(_i17.AppSettings? target) => super.noSuchMethod(
    Invocation.method(#scheduleWrite, [target]),
    returnValueForMissingStub: null,
  );

  @override
  _i23.Future<void> persistNow(_i17.AppSettings? fallback) =>
      (super.noSuchMethod(
            Invocation.method(#persistNow, [fallback]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> persistImmediately(_i17.AppSettings? value) =>
      (super.noSuchMethod(
            Invocation.method(#persistImmediately, [value]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<void> quarantine(String? box, String? originalKey, String? raw) =>
      (super.noSuchMethod(
            Invocation.method(#quarantine, [box, originalKey, raw]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);
}

/// A class which mocks [BackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupService extends _i1.Mock implements _i45.BackupService {
  @override
  _i23.Future<void> exportBackup() =>
      (super.noSuchMethod(
            Invocation.method(#exportBackup, []),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i46.CvBackupBundle?> pickImportFile() =>
      (super.noSuchMethod(
            Invocation.method(#pickImportFile, []),
            returnValue: _i23.Future<_i46.CvBackupBundle?>.value(),
            returnValueForMissingStub:
                _i23.Future<_i46.CvBackupBundle?>.value(),
          )
          as _i23.Future<_i46.CvBackupBundle?>);

  @override
  _i23.Future<void> applyImport(_i46.CvBackupBundle? bundle) =>
      (super.noSuchMethod(
            Invocation.method(#applyImport, [bundle]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);
}

/// A class which mocks [FileUploadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileUploadService extends _i1.Mock implements _i47.FileUploadService {
  @override
  _i23.Future<_i37.Uint8List?> pickJsonFile() =>
      (super.noSuchMethod(
            Invocation.method(#pickJsonFile, []),
            returnValue: _i23.Future<_i37.Uint8List?>.value(),
            returnValueForMissingStub: _i23.Future<_i37.Uint8List?>.value(),
          )
          as _i23.Future<_i37.Uint8List?>);

  @override
  _i23.Future<_i37.Uint8List?> pickPdfFile() =>
      (super.noSuchMethod(
            Invocation.method(#pickPdfFile, []),
            returnValue: _i23.Future<_i37.Uint8List?>.value(),
            returnValueForMissingStub: _i23.Future<_i37.Uint8List?>.value(),
          )
          as _i23.Future<_i37.Uint8List?>);
}

/// A class which mocks [PdfExtractionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfExtractionService extends _i1.Mock
    implements _i48.PdfExtractionService {
  @override
  _i23.Future<_i18.AtsExtractedDocument> extract(_i37.Uint8List? bytes) =>
      (super.noSuchMethod(
            Invocation.method(#extract, [bytes]),
            returnValue: _i23.Future<_i18.AtsExtractedDocument>.value(
              _FakeAtsExtractedDocument_19(
                this,
                Invocation.method(#extract, [bytes]),
              ),
            ),
            returnValueForMissingStub:
                _i23.Future<_i18.AtsExtractedDocument>.value(
                  _FakeAtsExtractedDocument_19(
                    this,
                    Invocation.method(#extract, [bytes]),
                  ),
                ),
          )
          as _i23.Future<_i18.AtsExtractedDocument>);

  @override
  _i23.Future<_i19.AtsTextMatrix> getPageViewportTransform(
    _i37.Uint8List? bytes, {
    required int? pageIndex,
    required double? dpi,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPageViewportTransform,
              [bytes],
              {#pageIndex: pageIndex, #dpi: dpi},
            ),
            returnValue: _i23.Future<_i19.AtsTextMatrix>.value(
              _FakeAtsTextMatrix_20(
                this,
                Invocation.method(
                  #getPageViewportTransform,
                  [bytes],
                  {#pageIndex: pageIndex, #dpi: dpi},
                ),
              ),
            ),
            returnValueForMissingStub: _i23.Future<_i19.AtsTextMatrix>.value(
              _FakeAtsTextMatrix_20(
                this,
                Invocation.method(
                  #getPageViewportTransform,
                  [bytes],
                  {#pageIndex: pageIndex, #dpi: dpi},
                ),
              ),
            ),
          )
          as _i23.Future<_i19.AtsTextMatrix>);
}

/// A class which mocks [AtsAnalyzerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtsAnalyzerService extends _i1.Mock
    implements _i49.AtsAnalyzerService {
  @override
  _i20.AtsAnalysisResult analyze(_i18.AtsExtractedDocument? document) =>
      (super.noSuchMethod(
            Invocation.method(#analyze, [document]),
            returnValue: _FakeAtsAnalysisResult_21(
              this,
              Invocation.method(#analyze, [document]),
            ),
            returnValueForMissingStub: _FakeAtsAnalysisResult_21(
              this,
              Invocation.method(#analyze, [document]),
            ),
          )
          as _i20.AtsAnalysisResult);
}

/// A class which mocks [LlmService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLlmService extends _i1.Mock implements _i50.LlmService {
  @override
  _i23.Future<void> testConnection(String? providerId, String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, [providerId, apiKey]),
            returnValue: _i23.Future<void>.value(),
            returnValueForMissingStub: _i23.Future<void>.value(),
          )
          as _i23.Future<void>);

  @override
  _i23.Future<_i21.LlmJsonResponse> completeJson({
    required String? providerId,
    required String? modelId,
    required String? apiKey,
    required String? systemPrompt,
    required String? userContent,
    required _i51.JsonSchema? schema,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeJson, [], {
              #providerId: providerId,
              #modelId: modelId,
              #apiKey: apiKey,
              #systemPrompt: systemPrompt,
              #userContent: userContent,
              #schema: schema,
            }),
            returnValue: _i23.Future<_i21.LlmJsonResponse>.value(
              _FakeLlmJsonResponse_22(
                this,
                Invocation.method(#completeJson, [], {
                  #providerId: providerId,
                  #modelId: modelId,
                  #apiKey: apiKey,
                  #systemPrompt: systemPrompt,
                  #userContent: userContent,
                  #schema: schema,
                }),
              ),
            ),
            returnValueForMissingStub: _i23.Future<_i21.LlmJsonResponse>.value(
              _FakeLlmJsonResponse_22(
                this,
                Invocation.method(#completeJson, [], {
                  #providerId: providerId,
                  #modelId: modelId,
                  #apiKey: apiKey,
                  #systemPrompt: systemPrompt,
                  #userContent: userContent,
                  #schema: schema,
                }),
              ),
            ),
          )
          as _i23.Future<_i21.LlmJsonResponse>);
}
