// Mocks generated by Mockito 5.4.6 from annotations
// in cv_forge/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i26;
import 'dart:typed_data' as _i41;
import 'dart:ui' as _i31;

import 'package:cv_forge/models/ats/ats_analysis_result.dart' as _i21;
import 'package:cv_forge/models/ats/ats_extracted_document.dart' as _i19;
import 'package:cv_forge/models/ats/ats_text_node.dart' as _i20;
import 'package:cv_forge/models/backup/cv_backup_bundle.dart' as _i18;
import 'package:cv_forge/models/draft/cv_draft.dart' as _i14;
import 'package:cv_forge/models/draft/cv_section_type.dart' as _i39;
import 'package:cv_forge/models/drive/drive_file_snapshot.dart' as _i24;
import 'package:cv_forge/models/drive/drive_sync_status.dart' as _i60;
import 'package:cv_forge/models/llm/copilot_result.dart' as _i23;
import 'package:cv_forge/models/llm/json_schema.dart' as _i55;
import 'package:cv_forge/models/llm/llm_json_response.dart' as _i22;
import 'package:cv_forge/models/render/region_profile.dart' as _i38;
import 'package:cv_forge/models/render/resolved_cv.dart' as _i46;
import 'package:cv_forge/models/settings/app_settings.dart' as _i17;
import 'package:cv_forge/models/settings/cv_preferences.dart' as _i49;
import 'package:cv_forge/models/vault/bullet_owner.dart' as _i35;
import 'package:cv_forge/models/vault/contact_basics.dart' as _i33;
import 'package:cv_forge/models/vault/cv_bullet.dart' as _i13;
import 'package:cv_forge/models/vault/cv_vault.dart' as _i4;
import 'package:cv_forge/models/vault/education.dart' as _i10;
import 'package:cv_forge/models/vault/experience.dart' as _i6;
import 'package:cv_forge/models/vault/hobby_item.dart' as _i11;
import 'package:cv_forge/models/vault/profile_link.dart' as _i5;
import 'package:cv_forge/models/vault/project.dart' as _i7;
import 'package:cv_forge/models/vault/publication.dart' as _i12;
import 'package:cv_forge/models/vault/skill.dart' as _i9;
import 'package:cv_forge/models/vault/skill_category.dart' as _i8;
import 'package:cv_forge/models/vault/year_month.dart' as _i34;
import 'package:cv_forge/services/ats_analyzer_service.dart' as _i53;
import 'package:cv_forge/services/backup_service.dart' as _i50;
import 'package:cv_forge/services/copilot_service.dart' as _i56;
import 'package:cv_forge/services/draft_service.dart' as _i36;
import 'package:cv_forge/services/drive_api_client_service.dart' as _i58;
import 'package:cv_forge/services/drive_sync_service.dart' as _i59;
import 'package:cv_forge/services/file_download_service.dart' as _i40;
import 'package:cv_forge/services/file_upload_service.dart' as _i51;
import 'package:cv_forge/services/font_service.dart' as _i44;
import 'package:cv_forge/services/google_auth_service.dart' as _i61;
import 'package:cv_forge/services/llm_service.dart' as _i54;
import 'package:cv_forge/services/local_storage_service.dart' as _i3;
import 'package:cv_forge/services/pdf_export_service.dart' as _i45;
import 'package:cv_forge/services/pdf_extraction_service.dart' as _i52;
import 'package:cv_forge/services/settings_service.dart' as _i48;
import 'package:cv_forge/services/template_registry_service.dart' as _i43;
import 'package:cv_forge/services/template_thumbnail_service.dart' as _i57;
import 'package:cv_forge/services/vault_service.dart' as _i32;
import 'package:cv_forge/templates/cv_template.dart' as _i15;
import 'package:cv_forge/templates/design/cv_font_set.dart' as _i16;
import 'package:file_saver/file_saver.dart' as _i42;
import 'package:flutter/material.dart' as _i27;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i37;
import 'package:pdf/pdf.dart' as _i47;
import 'package:stacked/stacked.dart' as _i2;
import 'package:stacked_services/src/dialog/dialog_service.dart' as _i28;
import 'package:stacked_services/src/models/overlay_request.dart' as _i29;
import 'package:stacked_services/src/models/overlay_response.dart' as _i30;
import 'package:stacked_services/src/navigation/router_service.dart' as _i25;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRootStackRouter_0 extends _i1.SmartFake
    implements _i2.RootStackRouter {
  _FakeRootStackRouter_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteData_1 extends _i1.SmartFake implements _i2.RouteData {
  _FakeRouteData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoutingController_2 extends _i1.SmartFake
    implements _i2.RoutingController {
  _FakeRoutingController_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalStorageService_3 extends _i1.SmartFake
    implements _i3.LocalStorageService {
  _FakeLocalStorageService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCvVault_4 extends _i1.SmartFake implements _i4.CvVault {
  _FakeCvVault_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReactiveValue_5<T> extends _i1.SmartFake
    implements _i2.ReactiveValue<T> {
  _FakeReactiveValue_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileLink_6 extends _i1.SmartFake implements _i5.ProfileLink {
  _FakeProfileLink_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExperience_7 extends _i1.SmartFake implements _i6.Experience {
  _FakeExperience_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProject_8 extends _i1.SmartFake implements _i7.Project {
  _FakeProject_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSkillCategory_9 extends _i1.SmartFake implements _i8.SkillCategory {
  _FakeSkillCategory_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSkill_10 extends _i1.SmartFake implements _i9.Skill {
  _FakeSkill_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEducation_11 extends _i1.SmartFake implements _i10.Education {
  _FakeEducation_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHobbyItem_12 extends _i1.SmartFake implements _i11.HobbyItem {
  _FakeHobbyItem_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePublication_13 extends _i1.SmartFake implements _i12.Publication {
  _FakePublication_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCvBullet_14 extends _i1.SmartFake implements _i13.CvBullet {
  _FakeCvBullet_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCvDraft_15 extends _i1.SmartFake implements _i14.CvDraft {
  _FakeCvDraft_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCvTemplate_16 extends _i1.SmartFake implements _i15.CvTemplate {
  _FakeCvTemplate_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCvFontSet_17 extends _i1.SmartFake implements _i16.CvFontSet {
  _FakeCvFontSet_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppSettings_18 extends _i1.SmartFake implements _i17.AppSettings {
  _FakeAppSettings_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCvBackupBundle_19 extends _i1.SmartFake
    implements _i18.CvBackupBundle {
  _FakeCvBackupBundle_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtsExtractedDocument_20 extends _i1.SmartFake
    implements _i19.AtsExtractedDocument {
  _FakeAtsExtractedDocument_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtsTextMatrix_21 extends _i1.SmartFake
    implements _i20.AtsTextMatrix {
  _FakeAtsTextMatrix_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtsAnalysisResult_22 extends _i1.SmartFake
    implements _i21.AtsAnalysisResult {
  _FakeAtsAnalysisResult_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLlmJsonResponse_23 extends _i1.SmartFake
    implements _i22.LlmJsonResponse {
  _FakeLlmJsonResponse_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCopilotResult_24 extends _i1.SmartFake
    implements _i23.CopilotResult {
  _FakeCopilotResult_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriveFileSnapshot_25 extends _i1.SmartFake
    implements _i24.DriveFileSnapshot {
  _FakeDriveFileSnapshot_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_26 extends _i1.SmartFake implements Duration {
  _FakeDuration_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RouterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouterService extends _i1.Mock implements _i25.RouterService {
  @override
  _i2.RootStackRouter get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeRootStackRouter_0(
              this,
              Invocation.getter(#router),
            ),
            returnValueForMissingStub: _FakeRootStackRouter_0(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i2.RootStackRouter);

  @override
  List<_i2.StackedPage<dynamic>> get stack =>
      (super.noSuchMethod(
            Invocation.getter(#stack),
            returnValue: <_i2.StackedPage<dynamic>>[],
            returnValueForMissingStub: <_i2.StackedPage<dynamic>>[],
          )
          as List<_i2.StackedPage<dynamic>>);

  @override
  _i2.RouteData get topRoute =>
      (super.noSuchMethod(
            Invocation.getter(#topRoute),
            returnValue: _FakeRouteData_1(this, Invocation.getter(#topRoute)),
            returnValueForMissingStub: _FakeRouteData_1(
              this,
              Invocation.getter(#topRoute),
            ),
          )
          as _i2.RouteData);

  @override
  set router(_i2.RootStackRouter? value) => super.noSuchMethod(
    Invocation.setter(#router, value),
    returnValueForMissingStub: null,
  );

  @override
  dynamic setRouter(_i2.RootStackRouter? router) => super.noSuchMethod(
    Invocation.method(#setRouter, [router]),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<dynamic> navigateTo(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#navigateTo, [route], {#onFailure: onFailure}),
            returnValue: _i26.Future<dynamic>.value(),
            returnValueForMissingStub: _i26.Future<dynamic>.value(),
          )
          as _i26.Future<dynamic>);

  @override
  _i26.Future<void> navigateToPath({
    required String? path,
    bool? includePrefixMatches = false,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#navigateToPath, [], {
              #path: path,
              #includePrefixMatches: includePrefixMatches,
              #onFailure: onFailure,
            }),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<T?> navigateWithTransition<T extends Object?>(
    _i27.Widget? widget, {
    _i27.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigateWithTransition,
              [widget],
              {
                #transitionBuilder: transitionBuilder,
                #fullscreenDialog: fullscreenDialog,
                #transitionDuration: transitionDuration,
              },
            ),
            returnValue: _i26.Future<T?>.value(),
            returnValueForMissingStub: _i26.Future<T?>.value(),
          )
          as _i26.Future<T?>);

  @override
  _i26.Future<T?> replaceWith<T extends Object?>(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replaceWith, [route], {#onFailure: onFailure}),
            returnValue: _i26.Future<T?>.value(),
            returnValueForMissingStub: _i26.Future<T?>.value(),
          )
          as _i26.Future<T?>);

  @override
  _i26.Future<void> clearStackAndShow(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #clearStackAndShow,
              [route],
              {#onFailure: onFailure},
            ),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> clearStackAndShowView(
    _i27.Widget? widget, {
    _i27.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #clearStackAndShowView,
              [widget],
              {
                #transitionBuilder: transitionBuilder,
                #fullscreenDialog: fullscreenDialog,
                #transitionDuration: transitionDuration,
              },
            ),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  void popForced<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#popForced, [result]),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<bool> pop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
            Invocation.method(#pop, [result]),
            returnValue: _i26.Future<bool>.value(false),
            returnValueForMissingStub: _i26.Future<bool>.value(false),
          )
          as _i26.Future<bool>);

  @override
  void back<T extends Object?>({T? result}) => super.noSuchMethod(
    Invocation.method(#back, [], {#result: result}),
    returnValueForMissingStub: null,
  );

  @override
  _i2.RoutingController topMostRouter({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
            Invocation.method(#topMostRouter, [], {
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: _FakeRoutingController_2(
              this,
              Invocation.method(#topMostRouter, [], {
                #ignorePagelessRoutes: ignorePagelessRoutes,
              }),
            ),
            returnValueForMissingStub: _FakeRoutingController_2(
              this,
              Invocation.method(#topMostRouter, [], {
                #ignorePagelessRoutes: ignorePagelessRoutes,
              }),
            ),
          )
          as _i2.RoutingController);

  @override
  _i26.Future<T?> pushNativeRoute<T extends Object?>(_i27.Route<T>? route) =>
      (super.noSuchMethod(
            Invocation.method(#pushNativeRoute, [route]),
            returnValue: _i26.Future<T?>.value(),
            returnValueForMissingStub: _i26.Future<T?>.value(),
          )
          as _i26.Future<T?>);
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i28.DialogService {
  @override
  void registerCustomDialogBuilders(
    Map<dynamic, _i28.DialogBuilder>? builders,
  ) => super.noSuchMethod(
    Invocation.method(#registerCustomDialogBuilders, [builders]),
    returnValueForMissingStub: null,
  );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i27.Widget Function(
      _i27.BuildContext,
      _i29.DialogRequest<dynamic>,
      dynamic Function(_i30.DialogResponse<dynamic>),
    )?
    builder,
  }) => super.noSuchMethod(
    Invocation.method(#registerCustomDialogBuilder, [], {
      #variant: variant,
      #builder: builder,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<_i30.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i31.Color? cancelTitleColor,
    String? buttonTitle = 'Ok',
    _i31.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i27.RouteSettings? routeSettings,
    _i27.GlobalKey<_i27.NavigatorState>? navigatorKey,
    _i28.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showDialog, [], {
              #title: title,
              #description: description,
              #cancelTitle: cancelTitle,
              #cancelTitleColor: cancelTitleColor,
              #buttonTitle: buttonTitle,
              #buttonTitleColor: buttonTitleColor,
              #barrierDismissible: barrierDismissible,
              #routeSettings: routeSettings,
              #navigatorKey: navigatorKey,
              #dialogPlatform: dialogPlatform,
            }),
            returnValue: _i26.Future<_i30.DialogResponse<dynamic>?>.value(),
            returnValueForMissingStub:
                _i26.Future<_i30.DialogResponse<dynamic>?>.value(),
          )
          as _i26.Future<_i30.DialogResponse<dynamic>?>);

  @override
  _i26.Future<_i30.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i31.Color? barrierColor = const _i31.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = '',
    bool? useSafeArea = true,
    _i27.RouteSettings? routeSettings,
    _i27.GlobalKey<_i27.NavigatorState>? navigatorKey,
    _i27.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showCustomDialog, [], {
              #variant: variant,
              #title: title,
              #description: description,
              #hasImage: hasImage,
              #imageUrl: imageUrl,
              #showIconInMainButton: showIconInMainButton,
              #mainButtonTitle: mainButtonTitle,
              #showIconInSecondaryButton: showIconInSecondaryButton,
              #secondaryButtonTitle: secondaryButtonTitle,
              #showIconInAdditionalButton: showIconInAdditionalButton,
              #additionalButtonTitle: additionalButtonTitle,
              #takesInput: takesInput,
              #barrierColor: barrierColor,
              #barrierDismissible: barrierDismissible,
              #barrierLabel: barrierLabel,
              #useSafeArea: useSafeArea,
              #routeSettings: routeSettings,
              #navigatorKey: navigatorKey,
              #transitionBuilder: transitionBuilder,
              #customData: customData,
              #data: data,
            }),
            returnValue: _i26.Future<_i30.DialogResponse<T>?>.value(),
            returnValueForMissingStub:
                _i26.Future<_i30.DialogResponse<T>?>.value(),
          )
          as _i26.Future<_i30.DialogResponse<T>?>);

  @override
  _i26.Future<_i30.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = 'Cancel',
    _i31.Color? cancelTitleColor,
    String? confirmationTitle = 'Ok',
    _i31.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i27.RouteSettings? routeSettings,
    _i28.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showConfirmationDialog, [], {
              #title: title,
              #description: description,
              #cancelTitle: cancelTitle,
              #cancelTitleColor: cancelTitleColor,
              #confirmationTitle: confirmationTitle,
              #confirmationTitleColor: confirmationTitleColor,
              #barrierDismissible: barrierDismissible,
              #routeSettings: routeSettings,
              #dialogPlatform: dialogPlatform,
            }),
            returnValue: _i26.Future<_i30.DialogResponse<dynamic>?>.value(),
            returnValueForMissingStub:
                _i26.Future<_i30.DialogResponse<dynamic>?>.value(),
          )
          as _i26.Future<_i30.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i30.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(#completeDialog, [response]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i3.LocalStorageService {
  @override
  _i26.Future<void> ensureInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#ensureInitialized, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<String?> read(String? boxName, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [boxName, key]),
            returnValue: _i26.Future<String?>.value(),
            returnValueForMissingStub: _i26.Future<String?>.value(),
          )
          as _i26.Future<String?>);

  @override
  _i26.Future<void> write(String? boxName, String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#write, [boxName, key, value]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> delete(String? boxName, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [boxName, key]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}

/// A class which mocks [VaultService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaultService extends _i1.Mock implements _i32.VaultService {
  @override
  _i3.LocalStorageService get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeLocalStorageService_3(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeLocalStorageService_3(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i3.LocalStorageService);

  @override
  _i4.CvVault get vault =>
      (super.noSuchMethod(
            Invocation.getter(#vault),
            returnValue: _FakeCvVault_4(this, Invocation.getter(#vault)),
            returnValueForMissingStub: _FakeCvVault_4(
              this,
              Invocation.getter(#vault),
            ),
          )
          as _i4.CvVault);

  @override
  int get listenersCount =>
      (super.noSuchMethod(
            Invocation.getter(#listenersCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i2.ReactiveValue<Object?> get persistErrorNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#persistErrorNotifier),
            returnValue: _FakeReactiveValue_5<Object?>(
              this,
              Invocation.getter(#persistErrorNotifier),
            ),
            returnValueForMissingStub: _FakeReactiveValue_5<Object?>(
              this,
              Invocation.getter(#persistErrorNotifier),
            ),
          )
          as _i2.ReactiveValue<Object?>);

  @override
  set persistError(Object? value) => super.noSuchMethod(
    Invocation.setter(#persistError, value),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> loadFromStorage() =>
      (super.noSuchMethod(
            Invocation.method(#loadFromStorage, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> loadExampleVault() =>
      (super.noSuchMethod(
            Invocation.method(#loadExampleVault, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> clearVault() =>
      (super.noSuchMethod(
            Invocation.method(#clearVault, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> updateBasics(_i33.ContactBasics? basics) =>
      (super.noSuchMethod(
            Invocation.method(#updateBasics, [basics]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i5.ProfileLink> addProfileLink({
    required String? label,
    required String? url,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addProfileLink, [], {#label: label, #url: url}),
            returnValue: _i26.Future<_i5.ProfileLink>.value(
              _FakeProfileLink_6(
                this,
                Invocation.method(#addProfileLink, [], {
                  #label: label,
                  #url: url,
                }),
              ),
            ),
            returnValueForMissingStub: _i26.Future<_i5.ProfileLink>.value(
              _FakeProfileLink_6(
                this,
                Invocation.method(#addProfileLink, [], {
                  #label: label,
                  #url: url,
                }),
              ),
            ),
          )
          as _i26.Future<_i5.ProfileLink>);

  @override
  _i26.Future<void> updateProfileLink(_i5.ProfileLink? link) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfileLink, [link]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> deleteProfileLink(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfileLink, [id]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> updateReferencesNote(String? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateReferencesNote, [note]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i6.Experience> addExperience({
    required String? role,
    required String? company,
    required String? location,
    required _i34.YearMonth? start,
    _i34.YearMonth? end,
    bool? isCurrent = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addExperience, [], {
              #role: role,
              #company: company,
              #location: location,
              #start: start,
              #end: end,
              #isCurrent: isCurrent,
            }),
            returnValue: _i26.Future<_i6.Experience>.value(
              _FakeExperience_7(
                this,
                Invocation.method(#addExperience, [], {
                  #role: role,
                  #company: company,
                  #location: location,
                  #start: start,
                  #end: end,
                  #isCurrent: isCurrent,
                }),
              ),
            ),
            returnValueForMissingStub: _i26.Future<_i6.Experience>.value(
              _FakeExperience_7(
                this,
                Invocation.method(#addExperience, [], {
                  #role: role,
                  #company: company,
                  #location: location,
                  #start: start,
                  #end: end,
                  #isCurrent: isCurrent,
                }),
              ),
            ),
          )
          as _i26.Future<_i6.Experience>);

  @override
  _i26.Future<void> updateExperience(_i6.Experience? experience) =>
      (super.noSuchMethod(
            Invocation.method(#updateExperience, [experience]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> deleteExperience(String? experienceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExperience, [experienceId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> groupExperience(
    String? experienceId,
    String? withExperienceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#groupExperience, [
              experienceId,
              withExperienceId,
            ]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i7.Project> addProject({required String? title, String? link}) =>
      (super.noSuchMethod(
            Invocation.method(#addProject, [], {#title: title, #link: link}),
            returnValue: _i26.Future<_i7.Project>.value(
              _FakeProject_8(
                this,
                Invocation.method(#addProject, [], {
                  #title: title,
                  #link: link,
                }),
              ),
            ),
            returnValueForMissingStub: _i26.Future<_i7.Project>.value(
              _FakeProject_8(
                this,
                Invocation.method(#addProject, [], {
                  #title: title,
                  #link: link,
                }),
              ),
            ),
          )
          as _i26.Future<_i7.Project>);

  @override
  _i26.Future<void> updateProject(_i7.Project? project) =>
      (super.noSuchMethod(
            Invocation.method(#updateProject, [project]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> deleteProject(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProject, [projectId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i8.SkillCategory> addSkillCategory(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#addSkillCategory, [name]),
            returnValue: _i26.Future<_i8.SkillCategory>.value(
              _FakeSkillCategory_9(
                this,
                Invocation.method(#addSkillCategory, [name]),
              ),
            ),
            returnValueForMissingStub: _i26.Future<_i8.SkillCategory>.value(
              _FakeSkillCategory_9(
                this,
                Invocation.method(#addSkillCategory, [name]),
              ),
            ),
          )
          as _i26.Future<_i8.SkillCategory>);

  @override
  _i26.Future<void> updateSkillCategory(_i8.SkillCategory? category) =>
      (super.noSuchMethod(
            Invocation.method(#updateSkillCategory, [category]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> deleteSkillCategory(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSkillCategory, [categoryId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i9.Skill> addSkill(String? categoryId, String? label) =>
      (super.noSuchMethod(
            Invocation.method(#addSkill, [categoryId, label]),
            returnValue: _i26.Future<_i9.Skill>.value(
              _FakeSkill_10(
                this,
                Invocation.method(#addSkill, [categoryId, label]),
              ),
            ),
            returnValueForMissingStub: _i26.Future<_i9.Skill>.value(
              _FakeSkill_10(
                this,
                Invocation.method(#addSkill, [categoryId, label]),
              ),
            ),
          )
          as _i26.Future<_i9.Skill>);

  @override
  _i26.Future<void> updateSkill(String? categoryId, _i9.Skill? skill) =>
      (super.noSuchMethod(
            Invocation.method(#updateSkill, [categoryId, skill]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> deleteSkill(String? categoryId, String? skillId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSkill, [categoryId, skillId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i10.Education> addEducation({
    required String? qualification,
    required String? institution,
    String? location,
    int? year,
    String? grade,
    String? details,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addEducation, [], {
              #qualification: qualification,
              #institution: institution,
              #location: location,
              #year: year,
              #grade: grade,
              #details: details,
            }),
            returnValue: _i26.Future<_i10.Education>.value(
              _FakeEducation_11(
                this,
                Invocation.method(#addEducation, [], {
                  #qualification: qualification,
                  #institution: institution,
                  #location: location,
                  #year: year,
                  #grade: grade,
                  #details: details,
                }),
              ),
            ),
            returnValueForMissingStub: _i26.Future<_i10.Education>.value(
              _FakeEducation_11(
                this,
                Invocation.method(#addEducation, [], {
                  #qualification: qualification,
                  #institution: institution,
                  #location: location,
                  #year: year,
                  #grade: grade,
                  #details: details,
                }),
              ),
            ),
          )
          as _i26.Future<_i10.Education>);

  @override
  _i26.Future<void> updateEducation(_i10.Education? education) =>
      (super.noSuchMethod(
            Invocation.method(#updateEducation, [education]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> deleteEducation(String? educationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEducation, [educationId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i11.HobbyItem> addHobby(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#addHobby, [text]),
            returnValue: _i26.Future<_i11.HobbyItem>.value(
              _FakeHobbyItem_12(this, Invocation.method(#addHobby, [text])),
            ),
            returnValueForMissingStub: _i26.Future<_i11.HobbyItem>.value(
              _FakeHobbyItem_12(this, Invocation.method(#addHobby, [text])),
            ),
          )
          as _i26.Future<_i11.HobbyItem>);

  @override
  _i26.Future<void> updateHobby(_i11.HobbyItem? hobby) =>
      (super.noSuchMethod(
            Invocation.method(#updateHobby, [hobby]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> deleteHobby(String? hobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHobby, [hobbyId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i12.Publication> addPublication({
    required String? title,
    String? citation,
    String? link,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addPublication, [], {
              #title: title,
              #citation: citation,
              #link: link,
            }),
            returnValue: _i26.Future<_i12.Publication>.value(
              _FakePublication_13(
                this,
                Invocation.method(#addPublication, [], {
                  #title: title,
                  #citation: citation,
                  #link: link,
                }),
              ),
            ),
            returnValueForMissingStub: _i26.Future<_i12.Publication>.value(
              _FakePublication_13(
                this,
                Invocation.method(#addPublication, [], {
                  #title: title,
                  #citation: citation,
                  #link: link,
                }),
              ),
            ),
          )
          as _i26.Future<_i12.Publication>);

  @override
  _i26.Future<void> updatePublication(_i12.Publication? publication) =>
      (super.noSuchMethod(
            Invocation.method(#updatePublication, [publication]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> deletePublication(String? publicationId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePublication, [publicationId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i13.CvBullet> addBullet(
    _i35.BulletOwner? owner,
    String? ownerId, {
    String? label,
    required String? text,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addBullet,
              [owner, ownerId],
              {#label: label, #text: text},
            ),
            returnValue: _i26.Future<_i13.CvBullet>.value(
              _FakeCvBullet_14(
                this,
                Invocation.method(
                  #addBullet,
                  [owner, ownerId],
                  {#label: label, #text: text},
                ),
              ),
            ),
            returnValueForMissingStub: _i26.Future<_i13.CvBullet>.value(
              _FakeCvBullet_14(
                this,
                Invocation.method(
                  #addBullet,
                  [owner, ownerId],
                  {#label: label, #text: text},
                ),
              ),
            ),
          )
          as _i26.Future<_i13.CvBullet>);

  @override
  _i26.Future<void> updateBullet(
    _i35.BulletOwner? owner,
    String? ownerId,
    _i13.CvBullet? bullet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBullet, [owner, ownerId, bullet]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> deleteBullet(
    _i35.BulletOwner? owner,
    String? ownerId,
    String? bulletId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBullet, [owner, ownerId, bulletId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> reorderBullets(
    _i35.BulletOwner? owner,
    String? ownerId,
    List<String>? orderedBulletIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderBullets, [
              owner,
              ownerId,
              orderedBulletIds,
            ]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> replaceAll(_i4.CvVault? vault) =>
      (super.noSuchMethod(
            Invocation.method(#replaceAll, [vault]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> flushPendingWrites() =>
      (super.noSuchMethod(
            Invocation.method(#flushPendingWrites, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> writeToStorage(_i4.CvVault? value) =>
      (super.noSuchMethod(
            Invocation.method(#writeToStorage, [value]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(#listenToReactiveValues, [reactiveValues]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> ready() =>
      (super.noSuchMethod(
            Invocation.method(#ready, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  void scheduleWrite(_i4.CvVault? target) => super.noSuchMethod(
    Invocation.method(#scheduleWrite, [target]),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> persistNow(_i4.CvVault? fallback) =>
      (super.noSuchMethod(
            Invocation.method(#persistNow, [fallback]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> persistImmediately(_i4.CvVault? value) =>
      (super.noSuchMethod(
            Invocation.method(#persistImmediately, [value]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> quarantine(String? box, String? originalKey, String? raw) =>
      (super.noSuchMethod(
            Invocation.method(#quarantine, [box, originalKey, raw]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}

/// A class which mocks [DraftService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDraftService extends _i1.Mock implements _i36.DraftService {
  @override
  _i3.LocalStorageService get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeLocalStorageService_3(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeLocalStorageService_3(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i3.LocalStorageService);

  @override
  List<_i14.CvDraft> get drafts =>
      (super.noSuchMethod(
            Invocation.getter(#drafts),
            returnValue: <_i14.CvDraft>[],
            returnValueForMissingStub: <_i14.CvDraft>[],
          )
          as List<_i14.CvDraft>);

  @override
  _i14.CvDraft get draft =>
      (super.noSuchMethod(
            Invocation.getter(#draft),
            returnValue: _FakeCvDraft_15(this, Invocation.getter(#draft)),
            returnValueForMissingStub: _FakeCvDraft_15(
              this,
              Invocation.getter(#draft),
            ),
          )
          as _i14.CvDraft);

  @override
  bool get isFreshDraft =>
      (super.noSuchMethod(
            Invocation.getter(#isFreshDraft),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get listenersCount =>
      (super.noSuchMethod(
            Invocation.getter(#listenersCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i2.ReactiveValue<Object?> get persistErrorNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#persistErrorNotifier),
            returnValue: _FakeReactiveValue_5<Object?>(
              this,
              Invocation.getter(#persistErrorNotifier),
            ),
            returnValueForMissingStub: _FakeReactiveValue_5<Object?>(
              this,
              Invocation.getter(#persistErrorNotifier),
            ),
          )
          as _i2.ReactiveValue<Object?>);

  @override
  set persistError(Object? value) => super.noSuchMethod(
    Invocation.setter(#persistError, value),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> loadFromStorage() =>
      (super.noSuchMethod(
            Invocation.method(#loadFromStorage, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<String> createDraft({
    required String? name,
    String? notes = '',
    String? templateId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDraft, [], {
              #name: name,
              #notes: notes,
              #templateId: templateId,
            }),
            returnValue: _i26.Future<String>.value(
              _i37.dummyValue<String>(
                this,
                Invocation.method(#createDraft, [], {
                  #name: name,
                  #notes: notes,
                  #templateId: templateId,
                }),
              ),
            ),
            returnValueForMissingStub: _i26.Future<String>.value(
              _i37.dummyValue<String>(
                this,
                Invocation.method(#createDraft, [], {
                  #name: name,
                  #notes: notes,
                  #templateId: templateId,
                }),
              ),
            ),
          )
          as _i26.Future<String>);

  @override
  _i26.Future<void> openDraft(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#openDraft, [id]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> updateDraftDetails(
    String? id, {
    required String? name,
    required String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateDraftDetails,
              [id],
              {#name: name, #notes: notes},
            ),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<String> duplicateDraft(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#duplicateDraft, [id]),
            returnValue: _i26.Future<String>.value(
              _i37.dummyValue<String>(
                this,
                Invocation.method(#duplicateDraft, [id]),
              ),
            ),
            returnValueForMissingStub: _i26.Future<String>.value(
              _i37.dummyValue<String>(
                this,
                Invocation.method(#duplicateDraft, [id]),
              ),
            ),
          )
          as _i26.Future<String>);

  @override
  _i26.Future<void> deleteDraft(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDraft, [id]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> replaceAll(
    List<_i14.CvDraft>? drafts, {
    required String? activeDraftId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceAll,
              [drafts],
              {#activeDraftId: activeDraftId},
            ),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setTemplate(String? templateId) =>
      (super.noSuchMethod(
            Invocation.method(#setTemplate, [templateId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setRegion(_i38.RegionProfile? region) =>
      (super.noSuchMethod(
            Invocation.method(#setRegion, [region]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> selectAllFromVault({
    required List<String>? experienceIds,
    required Map<String, List<String>>? bulletIds,
    required List<String>? projectIds,
    required Map<String, List<String>>? projectBulletIds,
    required List<String>? skillIds,
    required List<String>? educationIds,
    required List<String>? hobbyIds,
    required List<String>? publicationIds,
    required Map<String, List<String>>? publicationBulletIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectAllFromVault, [], {
              #experienceIds: experienceIds,
              #bulletIds: bulletIds,
              #projectIds: projectIds,
              #projectBulletIds: projectBulletIds,
              #skillIds: skillIds,
              #educationIds: educationIds,
              #hobbyIds: hobbyIds,
              #publicationIds: publicationIds,
              #publicationBulletIds: publicationBulletIds,
            }),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setExperienceIncluded(
    String? experienceId, {
    required bool? included,
    List<String>? bulletIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setExperienceIncluded,
              [experienceId],
              {#included: included, #bulletIds: bulletIds},
            ),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setProjectIncluded(
    String? projectId, {
    required bool? included,
    List<String>? bulletIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setProjectIncluded,
              [projectId],
              {#included: included, #bulletIds: bulletIds},
            ),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setPublicationIncluded(
    String? publicationId, {
    required bool? included,
    List<String>? bulletIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setPublicationIncluded,
              [publicationId],
              {#included: included, #bulletIds: bulletIds},
            ),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setSkillIncluded(
    String? skillId, {
    required bool? included,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setSkillIncluded,
              [skillId],
              {#included: included},
            ),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setEducationIncluded(
    String? educationId, {
    required bool? included,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setEducationIncluded,
              [educationId],
              {#included: included},
            ),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setHobbyIncluded(
    String? hobbyId, {
    required bool? included,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setHobbyIncluded,
              [hobbyId],
              {#included: included},
            ),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setBulletIds(
    _i35.BulletOwner? owner,
    String? ownerId,
    List<String>? bulletIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setBulletIds, [owner, ownerId, bulletIds]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setSectionHidden(
    _i39.CvSectionType? type, {
    required bool? hidden,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSectionHidden, [type], {#hidden: hidden}),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setSectionOrder(List<_i39.CvSectionType>? order) =>
      (super.noSuchMethod(
            Invocation.method(#setSectionOrder, [order]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> resetSectionSettings() =>
      (super.noSuchMethod(
            Invocation.method(#resetSectionSettings, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setTargetJobDescription(String? jobDescription) =>
      (super.noSuchMethod(
            Invocation.method(#setTargetJobDescription, [jobDescription]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> applyCopilotResult(_i23.CopilotResult? result) =>
      (super.noSuchMethod(
            Invocation.method(#applyCopilotResult, [result]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<bool> undoCopilotPass() =>
      (super.noSuchMethod(
            Invocation.method(#undoCopilotPass, []),
            returnValue: _i26.Future<bool>.value(false),
            returnValueForMissingStub: _i26.Future<bool>.value(false),
          )
          as _i26.Future<bool>);

  @override
  _i26.Future<bool> hasCopilotUndoFor(String? draftId) =>
      (super.noSuchMethod(
            Invocation.method(#hasCopilotUndoFor, [draftId]),
            returnValue: _i26.Future<bool>.value(false),
            returnValueForMissingStub: _i26.Future<bool>.value(false),
          )
          as _i26.Future<bool>);

  @override
  _i26.Future<void> setTailoredSummary(String? summary) =>
      (super.noSuchMethod(
            Invocation.method(#setTailoredSummary, [summary]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setBulletOverride(String? bulletId, String? text) =>
      (super.noSuchMethod(
            Invocation.method(#setBulletOverride, [bulletId, text]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setHeadlineOverride(String? headline) =>
      (super.noSuchMethod(
            Invocation.method(#setHeadlineOverride, [headline]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setReferencesOverride(String? references) =>
      (super.noSuchMethod(
            Invocation.method(#setReferencesOverride, [references]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setEducationDetailsOverride(
    String? educationId,
    String? text,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setEducationDetailsOverride, [
              educationId,
              text,
            ]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> flushPendingWrites() =>
      (super.noSuchMethod(
            Invocation.method(#flushPendingWrites, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> writeToStorage(_i14.CvDraft? value) =>
      (super.noSuchMethod(
            Invocation.method(#writeToStorage, [value]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(#listenToReactiveValues, [reactiveValues]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> ready() =>
      (super.noSuchMethod(
            Invocation.method(#ready, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  void scheduleWrite(_i14.CvDraft? target) => super.noSuchMethod(
    Invocation.method(#scheduleWrite, [target]),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> persistNow(_i14.CvDraft? fallback) =>
      (super.noSuchMethod(
            Invocation.method(#persistNow, [fallback]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> persistImmediately(_i14.CvDraft? value) =>
      (super.noSuchMethod(
            Invocation.method(#persistImmediately, [value]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> quarantine(String? box, String? originalKey, String? raw) =>
      (super.noSuchMethod(
            Invocation.method(#quarantine, [box, originalKey, raw]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}

/// A class which mocks [FileDownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileDownloadService extends _i1.Mock
    implements _i40.FileDownloadService {
  @override
  _i26.Future<void> saveFile({
    required String? nameWithoutExtension,
    required _i41.Uint8List? bytes,
    required String? extension,
    required _i42.MimeType? mimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveFile, [], {
              #nameWithoutExtension: nameWithoutExtension,
              #bytes: bytes,
              #extension: extension,
              #mimeType: mimeType,
            }),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}

/// A class which mocks [TemplateRegistryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTemplateRegistryService extends _i1.Mock
    implements _i43.TemplateRegistryService {
  @override
  _i15.CvTemplate get defaultTemplate =>
      (super.noSuchMethod(
            Invocation.getter(#defaultTemplate),
            returnValue: _FakeCvTemplate_16(
              this,
              Invocation.getter(#defaultTemplate),
            ),
            returnValueForMissingStub: _FakeCvTemplate_16(
              this,
              Invocation.getter(#defaultTemplate),
            ),
          )
          as _i15.CvTemplate);

  @override
  List<_i15.CvTemplate> get available =>
      (super.noSuchMethod(
            Invocation.getter(#available),
            returnValue: <_i15.CvTemplate>[],
            returnValueForMissingStub: <_i15.CvTemplate>[],
          )
          as List<_i15.CvTemplate>);

  @override
  _i15.CvTemplate byId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#byId, [id]),
            returnValue: _FakeCvTemplate_16(
              this,
              Invocation.method(#byId, [id]),
            ),
            returnValueForMissingStub: _FakeCvTemplate_16(
              this,
              Invocation.method(#byId, [id]),
            ),
          )
          as _i15.CvTemplate);
}

/// A class which mocks [FontService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFontService extends _i1.Mock implements _i44.FontService {
  @override
  _i26.Future<_i16.CvFontSet> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i26.Future<_i16.CvFontSet>.value(
              _FakeCvFontSet_17(this, Invocation.method(#load, [])),
            ),
            returnValueForMissingStub: _i26.Future<_i16.CvFontSet>.value(
              _FakeCvFontSet_17(this, Invocation.method(#load, [])),
            ),
          )
          as _i26.Future<_i16.CvFontSet>);

  @override
  _i26.Future<void> warmUp() =>
      (super.noSuchMethod(
            Invocation.method(#warmUp, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}

/// A class which mocks [PdfExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfExportService extends _i1.Mock implements _i45.PdfExportService {
  @override
  _i26.Future<void> export({
    required _i46.ResolvedCv? cv,
    required String? templateId,
    required String? fullName,
    required String? draftName,
    _i47.PdfPageFormat? format = _i47.PdfPageFormat.a4,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#export, [], {
              #cv: cv,
              #templateId: templateId,
              #fullName: fullName,
              #draftName: draftName,
              #format: format,
            }),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i41.Uint8List> render({
    required _i46.ResolvedCv? cv,
    required String? templateId,
    _i47.PdfPageFormat? format = _i47.PdfPageFormat.a4,
    bool? compress = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#render, [], {
              #cv: cv,
              #templateId: templateId,
              #format: format,
              #compress: compress,
            }),
            returnValue: _i26.Future<_i41.Uint8List>.value(_i41.Uint8List(0)),
            returnValueForMissingStub: _i26.Future<_i41.Uint8List>.value(
              _i41.Uint8List(0),
            ),
          )
          as _i26.Future<_i41.Uint8List>);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i48.SettingsService {
  @override
  _i3.LocalStorageService get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeLocalStorageService_3(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeLocalStorageService_3(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i3.LocalStorageService);

  @override
  _i17.AppSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeAppSettings_18(
              this,
              Invocation.getter(#settings),
            ),
            returnValueForMissingStub: _FakeAppSettings_18(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i17.AppSettings);

  @override
  int get listenersCount =>
      (super.noSuchMethod(
            Invocation.getter(#listenersCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i2.ReactiveValue<Object?> get persistErrorNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#persistErrorNotifier),
            returnValue: _FakeReactiveValue_5<Object?>(
              this,
              Invocation.getter(#persistErrorNotifier),
            ),
            returnValueForMissingStub: _FakeReactiveValue_5<Object?>(
              this,
              Invocation.getter(#persistErrorNotifier),
            ),
          )
          as _i2.ReactiveValue<Object?>);

  @override
  set persistError(Object? value) => super.noSuchMethod(
    Invocation.setter(#persistError, value),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setAssistantProvider(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#setAssistantProvider, [providerId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setAssistantModel(String? modelId) =>
      (super.noSuchMethod(
            Invocation.method(#setAssistantModel, [modelId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> replacePreferences(_i49.CvPreferences? preferences) =>
      (super.noSuchMethod(
            Invocation.method(#replacePreferences, [preferences]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setLastBackupAt(DateTime? value) =>
      (super.noSuchMethod(
            Invocation.method(#setLastBackupAt, [value]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setRememberApiKey(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setRememberApiKey, [value]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setDefaultRegion(_i38.RegionProfile? region) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultRegion, [region]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> setDefaultSectionSettings({
    required List<_i39.CvSectionType>? order,
    required Set<_i39.CvSectionType>? hiddenSections,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultSectionSettings, [], {
              #order: order,
              #hiddenSections: hiddenSections,
            }),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<String?> apiKeyFor(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#apiKeyFor, [providerId]),
            returnValue: _i26.Future<String?>.value(),
            returnValueForMissingStub: _i26.Future<String?>.value(),
          )
          as _i26.Future<String?>);

  @override
  _i26.Future<void> setApiKey(String? providerId, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#setApiKey, [providerId, key]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> clearApiKey(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#clearApiKey, [providerId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> loadFromStorage() =>
      (super.noSuchMethod(
            Invocation.method(#loadFromStorage, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> writeToStorage(_i17.AppSettings? value) =>
      (super.noSuchMethod(
            Invocation.method(#writeToStorage, [value]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(#listenToReactiveValues, [reactiveValues]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> ready() =>
      (super.noSuchMethod(
            Invocation.method(#ready, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  void scheduleWrite(_i17.AppSettings? target) => super.noSuchMethod(
    Invocation.method(#scheduleWrite, [target]),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> persistNow(_i17.AppSettings? fallback) =>
      (super.noSuchMethod(
            Invocation.method(#persistNow, [fallback]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> persistImmediately(_i17.AppSettings? value) =>
      (super.noSuchMethod(
            Invocation.method(#persistImmediately, [value]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> quarantine(String? box, String? originalKey, String? raw) =>
      (super.noSuchMethod(
            Invocation.method(#quarantine, [box, originalKey, raw]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}

/// A class which mocks [BackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupService extends _i1.Mock implements _i50.BackupService {
  @override
  _i18.CvBackupBundle buildBundle() =>
      (super.noSuchMethod(
            Invocation.method(#buildBundle, []),
            returnValue: _FakeCvBackupBundle_19(
              this,
              Invocation.method(#buildBundle, []),
            ),
            returnValueForMissingStub: _FakeCvBackupBundle_19(
              this,
              Invocation.method(#buildBundle, []),
            ),
          )
          as _i18.CvBackupBundle);

  @override
  _i26.Future<void> exportBackup() =>
      (super.noSuchMethod(
            Invocation.method(#exportBackup, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i18.CvBackupBundle?> pickImportFile() =>
      (super.noSuchMethod(
            Invocation.method(#pickImportFile, []),
            returnValue: _i26.Future<_i18.CvBackupBundle?>.value(),
            returnValueForMissingStub:
                _i26.Future<_i18.CvBackupBundle?>.value(),
          )
          as _i26.Future<_i18.CvBackupBundle?>);

  @override
  _i26.Future<void> applyImport(_i18.CvBackupBundle? bundle) =>
      (super.noSuchMethod(
            Invocation.method(#applyImport, [bundle]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}

/// A class which mocks [FileUploadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileUploadService extends _i1.Mock implements _i51.FileUploadService {
  @override
  _i26.Future<_i41.Uint8List?> pickJsonFile() =>
      (super.noSuchMethod(
            Invocation.method(#pickJsonFile, []),
            returnValue: _i26.Future<_i41.Uint8List?>.value(),
            returnValueForMissingStub: _i26.Future<_i41.Uint8List?>.value(),
          )
          as _i26.Future<_i41.Uint8List?>);

  @override
  _i26.Future<_i41.Uint8List?> pickPdfFile() =>
      (super.noSuchMethod(
            Invocation.method(#pickPdfFile, []),
            returnValue: _i26.Future<_i41.Uint8List?>.value(),
            returnValueForMissingStub: _i26.Future<_i41.Uint8List?>.value(),
          )
          as _i26.Future<_i41.Uint8List?>);
}

/// A class which mocks [PdfExtractionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfExtractionService extends _i1.Mock
    implements _i52.PdfExtractionService {
  @override
  _i26.Future<_i19.AtsExtractedDocument> extract(_i41.Uint8List? bytes) =>
      (super.noSuchMethod(
            Invocation.method(#extract, [bytes]),
            returnValue: _i26.Future<_i19.AtsExtractedDocument>.value(
              _FakeAtsExtractedDocument_20(
                this,
                Invocation.method(#extract, [bytes]),
              ),
            ),
            returnValueForMissingStub:
                _i26.Future<_i19.AtsExtractedDocument>.value(
                  _FakeAtsExtractedDocument_20(
                    this,
                    Invocation.method(#extract, [bytes]),
                  ),
                ),
          )
          as _i26.Future<_i19.AtsExtractedDocument>);

  @override
  _i26.Future<_i20.AtsTextMatrix> getPageViewportTransform(
    _i41.Uint8List? bytes, {
    required int? pageIndex,
    required double? dpi,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPageViewportTransform,
              [bytes],
              {#pageIndex: pageIndex, #dpi: dpi},
            ),
            returnValue: _i26.Future<_i20.AtsTextMatrix>.value(
              _FakeAtsTextMatrix_21(
                this,
                Invocation.method(
                  #getPageViewportTransform,
                  [bytes],
                  {#pageIndex: pageIndex, #dpi: dpi},
                ),
              ),
            ),
            returnValueForMissingStub: _i26.Future<_i20.AtsTextMatrix>.value(
              _FakeAtsTextMatrix_21(
                this,
                Invocation.method(
                  #getPageViewportTransform,
                  [bytes],
                  {#pageIndex: pageIndex, #dpi: dpi},
                ),
              ),
            ),
          )
          as _i26.Future<_i20.AtsTextMatrix>);
}

/// A class which mocks [AtsAnalyzerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtsAnalyzerService extends _i1.Mock
    implements _i53.AtsAnalyzerService {
  @override
  _i21.AtsAnalysisResult analyze(_i19.AtsExtractedDocument? document) =>
      (super.noSuchMethod(
            Invocation.method(#analyze, [document]),
            returnValue: _FakeAtsAnalysisResult_22(
              this,
              Invocation.method(#analyze, [document]),
            ),
            returnValueForMissingStub: _FakeAtsAnalysisResult_22(
              this,
              Invocation.method(#analyze, [document]),
            ),
          )
          as _i21.AtsAnalysisResult);
}

/// A class which mocks [LlmService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLlmService extends _i1.Mock implements _i54.LlmService {
  @override
  _i26.Future<void> testConnection(String? providerId, String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, [providerId, apiKey]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i22.LlmJsonResponse> completeJson({
    required String? providerId,
    required String? modelId,
    required String? apiKey,
    required String? systemPrompt,
    required String? userContent,
    required _i55.JsonSchema? schema,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeJson, [], {
              #providerId: providerId,
              #modelId: modelId,
              #apiKey: apiKey,
              #systemPrompt: systemPrompt,
              #userContent: userContent,
              #schema: schema,
            }),
            returnValue: _i26.Future<_i22.LlmJsonResponse>.value(
              _FakeLlmJsonResponse_23(
                this,
                Invocation.method(#completeJson, [], {
                  #providerId: providerId,
                  #modelId: modelId,
                  #apiKey: apiKey,
                  #systemPrompt: systemPrompt,
                  #userContent: userContent,
                  #schema: schema,
                }),
              ),
            ),
            returnValueForMissingStub: _i26.Future<_i22.LlmJsonResponse>.value(
              _FakeLlmJsonResponse_23(
                this,
                Invocation.method(#completeJson, [], {
                  #providerId: providerId,
                  #modelId: modelId,
                  #apiKey: apiKey,
                  #systemPrompt: systemPrompt,
                  #userContent: userContent,
                  #schema: schema,
                }),
              ),
            ),
          )
          as _i26.Future<_i22.LlmJsonResponse>);
}

/// A class which mocks [CopilotService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCopilotService extends _i1.Mock implements _i56.CopilotService {
  @override
  _i26.Future<_i23.CopilotResult> runTailoringPass({
    required _i4.CvVault? vault,
    required String? jobDescription,
    required String? providerId,
    required String? modelId,
    required String? apiKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#runTailoringPass, [], {
              #vault: vault,
              #jobDescription: jobDescription,
              #providerId: providerId,
              #modelId: modelId,
              #apiKey: apiKey,
            }),
            returnValue: _i26.Future<_i23.CopilotResult>.value(
              _FakeCopilotResult_24(
                this,
                Invocation.method(#runTailoringPass, [], {
                  #vault: vault,
                  #jobDescription: jobDescription,
                  #providerId: providerId,
                  #modelId: modelId,
                  #apiKey: apiKey,
                }),
              ),
            ),
            returnValueForMissingStub: _i26.Future<_i23.CopilotResult>.value(
              _FakeCopilotResult_24(
                this,
                Invocation.method(#runTailoringPass, [], {
                  #vault: vault,
                  #jobDescription: jobDescription,
                  #providerId: providerId,
                  #modelId: modelId,
                  #apiKey: apiKey,
                }),
              ),
            ),
          )
          as _i26.Future<_i23.CopilotResult>);
}

/// A class which mocks [TemplateThumbnailService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTemplateThumbnailService extends _i1.Mock
    implements _i57.TemplateThumbnailService {
  @override
  _i26.Future<_i41.Uint8List> thumbnail({
    required _i46.ResolvedCv? cv,
    required String? templateId,
    required _i47.PdfPageFormat? format,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#thumbnail, [], {
              #cv: cv,
              #templateId: templateId,
              #format: format,
            }),
            returnValue: _i26.Future<_i41.Uint8List>.value(_i41.Uint8List(0)),
            returnValueForMissingStub: _i26.Future<_i41.Uint8List>.value(
              _i41.Uint8List(0),
            ),
          )
          as _i26.Future<_i41.Uint8List>);
}

/// A class which mocks [DriveApiClientService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveApiClientService extends _i1.Mock
    implements _i58.DriveApiClientService {
  @override
  _i26.Future<String?> fetchAccountEmail(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAccountEmail, [accessToken]),
            returnValue: _i26.Future<String?>.value(),
            returnValueForMissingStub: _i26.Future<String?>.value(),
          )
          as _i26.Future<String?>);

  @override
  _i26.Future<_i24.DriveFileSnapshot?> findFile(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#findFile, [accessToken]),
            returnValue: _i26.Future<_i24.DriveFileSnapshot?>.value(),
            returnValueForMissingStub:
                _i26.Future<_i24.DriveFileSnapshot?>.value(),
          )
          as _i26.Future<_i24.DriveFileSnapshot?>);

  @override
  _i26.Future<_i24.DriveFileSnapshot> createFile(
    String? accessToken,
    Map<String, dynamic>? json,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createFile, [accessToken, json]),
            returnValue: _i26.Future<_i24.DriveFileSnapshot>.value(
              _FakeDriveFileSnapshot_25(
                this,
                Invocation.method(#createFile, [accessToken, json]),
              ),
            ),
            returnValueForMissingStub:
                _i26.Future<_i24.DriveFileSnapshot>.value(
                  _FakeDriveFileSnapshot_25(
                    this,
                    Invocation.method(#createFile, [accessToken, json]),
                  ),
                ),
          )
          as _i26.Future<_i24.DriveFileSnapshot>);

  @override
  _i26.Future<Map<String, dynamic>> downloadFile(
    String? accessToken,
    String? fileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [accessToken, fileId]),
            returnValue: _i26.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i26.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i26.Future<Map<String, dynamic>>);

  @override
  _i26.Future<_i24.DriveFileSnapshot> updateFile(
    String? accessToken,
    String? fileId,
    Map<String, dynamic>? json,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateFile, [accessToken, fileId, json]),
            returnValue: _i26.Future<_i24.DriveFileSnapshot>.value(
              _FakeDriveFileSnapshot_25(
                this,
                Invocation.method(#updateFile, [accessToken, fileId, json]),
              ),
            ),
            returnValueForMissingStub:
                _i26.Future<_i24.DriveFileSnapshot>.value(
                  _FakeDriveFileSnapshot_25(
                    this,
                    Invocation.method(#updateFile, [accessToken, fileId, json]),
                  ),
                ),
          )
          as _i26.Future<_i24.DriveFileSnapshot>);

  @override
  _i26.Future<_i24.DriveFileSnapshot> fetchMetadata(
    String? accessToken,
    String? fileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMetadata, [accessToken, fileId]),
            returnValue: _i26.Future<_i24.DriveFileSnapshot>.value(
              _FakeDriveFileSnapshot_25(
                this,
                Invocation.method(#fetchMetadata, [accessToken, fileId]),
              ),
            ),
            returnValueForMissingStub:
                _i26.Future<_i24.DriveFileSnapshot>.value(
                  _FakeDriveFileSnapshot_25(
                    this,
                    Invocation.method(#fetchMetadata, [accessToken, fileId]),
                  ),
                ),
          )
          as _i26.Future<_i24.DriveFileSnapshot>);
}

/// A class which mocks [DriveSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveSyncService extends _i1.Mock implements _i59.DriveSyncService {
  @override
  Duration get idleDebounce =>
      (super.noSuchMethod(
            Invocation.getter(#idleDebounce),
            returnValue: _FakeDuration_26(
              this,
              Invocation.getter(#idleDebounce),
            ),
            returnValueForMissingStub: _FakeDuration_26(
              this,
              Invocation.getter(#idleDebounce),
            ),
          )
          as Duration);

  @override
  Duration get maxWait =>
      (super.noSuchMethod(
            Invocation.getter(#maxWait),
            returnValue: _FakeDuration_26(this, Invocation.getter(#maxWait)),
            returnValueForMissingStub: _FakeDuration_26(
              this,
              Invocation.getter(#maxWait),
            ),
          )
          as Duration);

  @override
  Duration get mergedNoticeDuration =>
      (super.noSuchMethod(
            Invocation.getter(#mergedNoticeDuration),
            returnValue: _FakeDuration_26(
              this,
              Invocation.getter(#mergedNoticeDuration),
            ),
            returnValueForMissingStub: _FakeDuration_26(
              this,
              Invocation.getter(#mergedNoticeDuration),
            ),
          )
          as Duration);

  @override
  _i60.DriveSyncStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i37.dummyValue<_i60.DriveSyncStatus>(
              this,
              Invocation.getter(#status),
            ),
            returnValueForMissingStub: _i37.dummyValue<_i60.DriveSyncStatus>(
              this,
              Invocation.getter(#status),
            ),
          )
          as _i60.DriveSyncStatus);

  @override
  bool get isAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#isAvailable),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get listenersCount =>
      (super.noSuchMethod(
            Invocation.getter(#listenersCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i26.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> syncNow() =>
      (super.noSuchMethod(
            Invocation.method(#syncNow, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> flushPendingWrites() =>
      (super.noSuchMethod(
            Invocation.method(#flushPendingWrites, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(#listenToReactiveValues, [reactiveValues]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GoogleAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthService extends _i1.Mock implements _i61.GoogleAuthService {
  @override
  bool get isConfigured =>
      (super.noSuchMethod(
            Invocation.getter(#isConfigured),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i26.Future<String?> silentAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#silentAccessToken, []),
            returnValue: _i26.Future<String?>.value(),
            returnValueForMissingStub: _i26.Future<String?>.value(),
          )
          as _i26.Future<String?>);

  @override
  _i26.Future<void> warmUp() =>
      (super.noSuchMethod(
            Invocation.method(#warmUp, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<String?> tokenOnNextUserGesture() =>
      (super.noSuchMethod(
            Invocation.method(#tokenOnNextUserGesture, []),
            returnValue: _i26.Future<String?>.value(),
            returnValueForMissingStub: _i26.Future<String?>.value(),
          )
          as _i26.Future<String?>);

  @override
  _i26.Future<String> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i26.Future<String>.value(
              _i37.dummyValue<String>(this, Invocation.method(#connect, [])),
            ),
            returnValueForMissingStub: _i26.Future<String>.value(
              _i37.dummyValue<String>(this, Invocation.method(#connect, [])),
            ),
          )
          as _i26.Future<String>);

  @override
  _i26.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}
